- id: '1643034412279'
  alias: Welcome Lights
  description: ''
  trigger:
  - platform: state
    entity_id: group.family
    to: home
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - service: homeassistant.turn_on
    target:
      entity_id: group.welcome_lights
