- id: '1643034412279'
  alias: Welcome Lights
  description: ''
  trigger:
  - platform: state
    entity_id: group.family
    from: away
    to: home
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - service: homeassistant.turn_on
    target:
      entity_id: group.welcome_lights
  - service: notify.parents
    data:
      message: Welcome lights turned on at {{now().strftime("%H:%M")}}
- id: debug_matt_location
  alias: Debug matt location
  trigger:
  - platform: state
    entity_id: device_tracker.matt_pixel_8_pro
    not_from:
  action:
  - service: notify.mobile_app_matt_pixel_8_pro
    data:
      message: Matt is at {{states('device_tracker.matt_pixel_8_pro')}} at {{now().strftime("%H:%M")}}
- id: open_garage_matt
  alias: Open garage when Matt drives home
  trigger:
  - platform: state
    entity_id: device_tracker.matt_pixel_8_pro
    from: not_home
    to:
    - home
    - HomeStreet1
    - HomeStreet2
  condition:
  - condition: state
    alias: Garage closed
    entity_id: cover.garage_door
    state: closed
  - condition: template
    alias: Phone connected to car
    value_template: '{{state_attr(''sensor.matt_pixel_8_pro_bluetooth_connection'',
      ''connected_paired_devices'') | contains(''B8:9F:09:62:F7:7F (BMW 93379)'')
      or state_attr(''sensor.matt_pixel_8_pro_bluetooth_connection'', ''connected_paired_devices'')
      | contains(''00:02:5B:BE:23:C0 (CAR6509)'') or state_attr(''sensor.matt_pixel_8_pro_bluetooth_connection'',
      ''connected_paired_devices'') | contains(''00:0A:30:92:D6:C7 (Mazda)'')}}'
  action:
  - service: cover.stop_cover
    target:
      entity_id: cover.garage_door
  - service: notify.mobile_app_matt_pixel_8_pro
    data:
      message: Matt arrived home, opening garage at {{now().strftime("%H:%M")}}
- id: open_garage_sara
  alias: Open garage when Sara drives home
  trigger:
  - platform: state
    entity_id:
    - device_tracker.saras_iphone_app
    from: not_home
    to:
    - home
    - HomeStreet1
    - HomeStreet2
  condition:
  - condition: state
    alias: Garage closed
    entity_id: cover.garage_door
    state: closed
  - condition: template
    alias: Phone connected to car
    value_template: '{{states(''sensor.saras_iphone14_ssid'') == ''DIRECT-BMW 93379''}}'
  action:
  - service: cover.stop_cover
    target:
      entity_id: cover.garage_door
  - service: notify.mobile_app_matt_pixel_8_pro
    data:
      message: Sara arrived home, opening garage at {{now().strftime("%H:%M")}}
  - service: notify.mobile_app_saras_iphone_2
    data:
      message: Sara arrived home, opening garage at {{now().strftime("%H:%M")}}
- id: garage_left_open_warn
  alias: Send a warning if the garage left open
  trigger:
  - platform: template
    value_template: '{{ not(is_state(''cover.garage_door'', ''closed''))}}'
    for: 00:05:00
  action:
  - service: notify.parents
    data:
      message: Garage left open! At {{now().strftime("%H:%M")}}
- id: garage_monitoring
  alias: Debug garage open & close
  trigger:
  - platform: state
    entity_id: cover.garage_door
  action:
  - service: notify.mobile_app_matt_pixel_8_pro
    data:
      message: Garage is {{states.cover.garage_door.state}} at {{now().strftime("%H:%M")}}
- id: sensor_lights
  alias: Sensor Lights
  description: Sensor lights combining both sensors and lights
  trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_motion_ac02_iaszone
    to: 'on'
  - platform: state
    entity_id: binary_sensor.front_yard_motion3_motion
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: 0
  action:
  - alias: Turn on the light
    service: light.turn_on
    target:
      entity_id:
      - light.front_yard_sensor_light
      - light.mailbox
      - light.bin_light
    data: {}
  - alias: Set bin light colour
    service: light.turn_on
    target:
      entity_id: light.bin_light
    data:
      brightness: 255
      hs_color: >-
        {% if is_state('sensor.brisbane_bin_day_recycle', 'on') %}
          [60,60]
        {% elif is_state('sensor.brisbane_bin_day', 'on') %}
          [128,33]
        {% else %}
          [0,0]
        {% endif %}
  - alias: Wait until there is no motion from either device
    wait_template: '{{ not(is_state(''binary_sensor.lumi_lumi_motion_ac02_iaszone'',
      ''on'')) and not(is_state(''binary_sensor.front_yard_motion3_motion'', ''on''))
      }}'
  - alias: Wait a while longer
    delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - alias: Turn off the light
    service: light.turn_off
    target:
      entity_id:
      - light.front_yard_sensor_light
      - light.mailbox
      - light.bin_light
    data: {}
  mode: restart
- id: '1720934399141'
  alias: Light Back On - Emily Sign
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.emily_sign
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 2
  condition: []
  action:
  - service: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.emily_sign
  mode: single
- id: '1720934399142'
  alias: Light Back On - Emily Makeup
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.emily_makeup
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 2
  condition: []
  action:
  - service: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.emily_makeup
  mode: single
- id: '1745786335394'
  alias: EmilyButton1-ReadingTime
  description: ''
  triggers:
  - device_id: 2d52c62b1bbcd0ec31a5901f9fcfa4ee
    domain: zha
    type: remote_button_short_press
    subtype: button_1
    trigger: device
  conditions: []
  actions:
  - action: script.emily_reading_time
    metadata: {}
    data: {}
  mode: single
- id: '1745786392915'
  alias: EmilyButton2-SleepTime
  description: ''
  triggers:
  - device_id: 2d52c62b1bbcd0ec31a5901f9fcfa4ee
    domain: zha
    type: remote_button_short_press
    subtype: button_2
    trigger: device
  conditions: []
  actions:
  - action: script.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: script.emily_sleep_time
  mode: single
- id: '1745786735917'
  alias: EmilyButton3-RgbLights
  description: ''
  triggers:
  - device_id: 2d52c62b1bbcd0ec31a5901f9fcfa4ee
    domain: zha
    type: remote_button_short_press
    subtype: button_3
    trigger: device
  conditions: []
  actions:
  - action: light.toggle
    metadata: {}
    data: {}
    target:
      entity_id: light.emily_rgb_strip
  mode: single
- id: '1745786785985'
  alias: EmilyButton4-Kitchen
  description: ''
  triggers:
  - device_id: 2d52c62b1bbcd0ec31a5901f9fcfa4ee
    domain: zha
    type: remote_button_short_press
    subtype: button_4
    trigger: device
  conditions: []
  actions:
  - action: light.toggle
    metadata: {}
    data: {}
    target:
      entity_id: light.kitchen
  mode: single
- id: '1745787427449'
  alias: TobyButton1-Reading
  description: ''
  triggers:
  - device_id: 5582c9a1d80e85a86f9d66ca5f750b98
    domain: zha
    type: remote_button_short_press
    subtype: button_1
    trigger: device
  conditions: []
  actions:
  - action: script.toby_reading_time
    metadata: {}
    data: {}
  mode: single
- id: '1745787483164'
  alias: TobyButton2-Sleep
  description: ''
  triggers:
  - device_id: 5582c9a1d80e85a86f9d66ca5f750b98
    domain: zha
    type: remote_button_short_press
    subtype: button_2
    trigger: device
  conditions: []
  actions:
  - action: script.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: script.toby_sleep_time
  mode: single
- id: '1745787544962'
  alias: TobyButton3-FrogLight
  description: ''
  triggers:
  - device_id: 5582c9a1d80e85a86f9d66ca5f750b98
    domain: zha
    type: remote_button_short_press
    subtype: button_3
    trigger: device
  conditions: []
  actions:
  - action: light.toggle
    metadata: {}
    data: {}
    target:
      entity_id: light.tobyfroglight
  mode: single
- id: '1745787601152'
  alias: TobyButton4-Hallway
  description: ''
  triggers:
  - device_id: 5582c9a1d80e85a86f9d66ca5f750b98
    domain: zha
    type: remote_button_short_press
    subtype: button_4
    trigger: device
  conditions: []
  actions:
  - action: light.toggle
    metadata: {}
    data: {}
    target:
      entity_id: group.hallway_lights
  mode: single
- id: '1745847668003'
  alias: EntryLongPress-LeavingHome
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - event.lights_entry_button_1
  conditions:
  - condition: state
    entity_id: event.lights_entry_button_1
    attribute: event_type
    state: Long Press
  actions:
  - action: script.turn_on
    target:
      entity_id: script.leaving_home
  mode: single
- id: EmilyLongPress-AllOff
  alias: EmilyLongPress-AllOff
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - event.lights_emily_button_1
  conditions:
  - condition: state
    entity_id: event.lights_emily_button_1
    attribute: event_type
    state: Long Press
  actions:
  - action: script.turn_on
    target:
      entity_id: script.emily_all_off
  mode: single
- id: TobyLongPress-AllOff
  alias: TobyLongPress-AllOff
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - event.lights_toby_button_1
  conditions:
  - condition: state
    entity_id: event.lights_toby_button_1
    attribute: event_type
    state: Long Press
  actions:
  - action: script.turn_on
    target:
      entity_id: script.toby_all_off
  mode: single
