- id: '1643034412279'
  alias: Welcome Lights
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - group.family
    from:
    - Away
    to:
    - home
  conditions:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  actions:
  - action: homeassistant.turn_on
    target:
      entity_id: group.welcome_lights
  - action: notify.parents
    data:
      message: Welcome lights turned on at {{now().strftime("%H:%M")}}
- id: debug_matt_location
  alias: Debug matt location
  trigger:
  - platform: state
    entity_id: device_tracker.matt_pixel_8_pro
    not_from:
  action:
  - service: notify.mobile_app_matt_pixel_8_pro
    data:
      message: Matt is at {{states('device_tracker.matt_pixel_8_pro')}} at {{now().strftime("%H:%M")}}
- id: open_garage_matt
  alias: Open garage when Matt drives home
  trigger:
  - platform: state
    entity_id: device_tracker.matt_pixel_8_pro
    from: not_home
    to:
    - home
    - HomeStreet1
    - HomeStreet2
  condition:
  - condition: state
    alias: Garage closed
    entity_id: cover.garage_door
    state: closed
  - condition: template
    alias: Phone connected to car
    value_template: '{{state_attr(''sensor.matt_pixel_8_pro_bluetooth_connection'',
      ''connected_paired_devices'') | contains(''B8:9F:09:62:F7:7F (BMW 93379)'')
      or state_attr(''sensor.matt_pixel_8_pro_bluetooth_connection'', ''connected_paired_devices'')
      | contains(''00:02:5B:BE:23:C0 (CAR6509)'') or state_attr(''sensor.matt_pixel_8_pro_bluetooth_connection'',
      ''connected_paired_devices'') | contains(''00:0A:30:92:D6:C7 (Mazda)'')}}'
  action:
  - service: cover.stop_cover
    target:
      entity_id: cover.garage_door
  - service: notify.mobile_app_matt_pixel_8_pro
    data:
      message: Matt arrived home, opening garage at {{now().strftime("%H:%M")}}
- id: open_garage_sara
  alias: Open garage when Sara drives home
  trigger:
  - platform: state
    entity_id:
    - device_tracker.saras_iphone_16
    from: not_home
    to:
    - home
    - HomeStreet1
    - HomeStreet2
  condition:
  - condition: state
    alias: Garage closed
    entity_id: cover.garage_door
    state: closed
  - condition: template
    alias: Phone connected to car
    value_template: '{{states(''sensor.saras_iphone_16_ssid'') == ''DIRECT-BMW 93379''}}'
  action:
  - service: cover.stop_cover
    target:
      entity_id: cover.garage_door
  - service: notify.mobile_app_matt_pixel_8_pro
    data:
      message: Sara arrived home, opening garage at {{now().strftime("%H:%M")}}
  - service: notify.mobile_app_saras_iphone_2
    data:
      message: Sara arrived home, opening garage at {{now().strftime("%H:%M")}}
- id: garage_left_open_warn
  alias: Send a warning if the garage left open
  trigger:
  - platform: template
    value_template: '{{ not(is_state(''cover.garage_door'', ''closed''))}}'
    for: 00:05:00
  action:
  - service: notify.parents
    data:
      message: Garage left open! At {{now().strftime("%H:%M")}}
      data:
        url: lovelace/2
        channel: alarm_stream
        priority: high
        critical: 1
        volume: 1.0
        ttl: 0
- id: garage_monitoring
  alias: Debug garage open & close
  trigger:
  - platform: state
    entity_id: cover.garage_door
  action:
  - service: notify.mobile_app_matt_pixel_8_pro
    data:
      message: Garage is {{states.cover.garage_door.state}} at {{now().strftime("%H:%M")}}
- id: sensor_lights
  alias: Sensor Lights
  description: Sensor lights combining both sensors and lights
  triggers:
  - entity_id: binary_sensor.front_yard_motion_stairs
    to: 'on'
    trigger: state
  - entity_id:
    - binary_sensor.front_yard_mailbox_motion
    to: 'on'
    trigger: state
  conditions:
  - condition: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: 0
  actions:
  - alias: Turn on the light
    target:
      entity_id:
      - light.front_yard_sensor_light
      - light.mailbox
      - light.bin_light
    data: {}
    action: light.turn_on
  - alias: Set bin light colour
    target:
      entity_id: light.bin_light
    data:
      brightness: 255
      hs_color: "{% if is_state('binary_sensor.brisbane_bin_day_recycle', 'on') %}\n
        \ [60,60]\n{% elif is_state('binary_sensor.brisbane_bin_day', 'on') %}\n  [128,100]\n{%
        else %}\n  [0,0]\n{% endif %}"
    action: light.turn_on
  - alias: Wait until there is no motion from either device
    wait_template: '{{ not(is_state(''binary_sensor.front_yard_motion_stairs'', ''on''))
      and not(is_state(''binary_sensor.front_yard_mailbox_motion'', ''on'')) }}'
  - alias: Wait a while longer
    delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - alias: Turn off the light
    target:
      entity_id:
      - light.front_yard_sensor_light
      - light.mailbox
      - light.bin_light
    data: {}
    action: light.turn_off
  mode: restart
- id: '1720934399141'
  alias: Light Back On - Emily Sign
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.emily_sign
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 2
  condition: []
  action:
  - service: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.emily_sign
  mode: single
- id: '1720934399142'
  alias: Light Back On - Emily Makeup
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.emily_makeup
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 2
  condition: []
  action:
  - service: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.emily_makeup
  mode: single
- id: '1745786335394'
  alias: EmilyButton1-ReadingTime
  description: ''
  triggers:
  - device_id: 2d52c62b1bbcd0ec31a5901f9fcfa4ee
    domain: zha
    type: remote_button_short_press
    subtype: button_1
    trigger: device
  conditions: []
  actions:
  - action: script.emily_reading_time
    metadata: {}
    data: {}
  mode: single
- id: '1745786392915'
  alias: EmilyButton2-SleepTime
  description: ''
  triggers:
  - device_id: 2d52c62b1bbcd0ec31a5901f9fcfa4ee
    domain: zha
    type: remote_button_short_press
    subtype: button_2
    trigger: device
  conditions: []
  actions:
  - action: script.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: script.emily_sleep_time
  mode: single
- id: '1745786735917'
  alias: EmilyButton3-RgbLights
  description: ''
  triggers:
  - device_id: 2d52c62b1bbcd0ec31a5901f9fcfa4ee
    domain: zha
    type: remote_button_short_press
    subtype: button_3
    trigger: device
  conditions: []
  actions:
  - action: light.toggle
    metadata: {}
    data: {}
    target:
      entity_id: light.emily_rgb_strip
  mode: single
- id: '1745786785985'
  alias: EmilyButton4-Kitchen
  description: ''
  triggers:
  - device_id: 2d52c62b1bbcd0ec31a5901f9fcfa4ee
    domain: zha
    type: remote_button_short_press
    subtype: button_4
    trigger: device
  conditions: []
  actions:
  - action: light.toggle
    metadata: {}
    data: {}
    target:
      entity_id: light.kitchen
  mode: single
- id: '1745787427449'
  alias: TobyButton1-Reading
  description: ''
  triggers:
  - device_id: 5582c9a1d80e85a86f9d66ca5f750b98
    domain: zha
    type: remote_button_short_press
    subtype: button_1
    trigger: device
  conditions: []
  actions:
  - action: script.toby_reading_time
    metadata: {}
    data: {}
  mode: single
- id: '1745787483164'
  alias: TobyButton2-Sleep
  description: ''
  triggers:
  - device_id: 5582c9a1d80e85a86f9d66ca5f750b98
    domain: zha
    type: remote_button_short_press
    subtype: button_2
    trigger: device
  conditions: []
  actions:
  - action: script.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: script.toby_sleep_time
  mode: single
- id: '1745787544962'
  alias: TobyButton3-FrogLight
  description: ''
  triggers:
  - device_id: 5582c9a1d80e85a86f9d66ca5f750b98
    domain: zha
    type: remote_button_short_press
    subtype: button_3
    trigger: device
  conditions: []
  actions:
  - action: light.toggle
    metadata: {}
    data: {}
    target:
      entity_id: light.tobyfroglight
  mode: single
- id: '1745787601152'
  alias: TobyButton4-Hallway
  description: ''
  triggers:
  - device_id: 5582c9a1d80e85a86f9d66ca5f750b98
    domain: zha
    type: remote_button_short_press
    subtype: button_4
    trigger: device
  conditions: []
  actions:
  - action: light.toggle
    metadata: {}
    data: {}
    target:
      entity_id: group.hallway_lights
  mode: single
- id: EmilyLongPress-AllOff
  alias: EmilyLongPress-AllOff
  description: ''
  triggers:
  - trigger: event.received
    target:
      entity_id: event.lights_emily_button_1
    options:
      event_type:
      - Long Press
  actions:
  - action: script.turn_on
    target:
      entity_id: script.emily_all_off
  mode: single
- id: TobyLongPress-AllOff
  alias: TobyLongPress-AllOff
  description: ''
  triggers:
  - trigger: event.received
    target:
      entity_id: event.lights_toby_button_1
    options:
      event_type:
      - Long Press
  actions:
  - action: script.turn_on
    target:
      entity_id: script.toby_all_off
  mode: single
- id: '1748697491265'
  alias: Storage sensor light
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.storage_motion
      light_target:
        entity_id: light.storage_light
- id: '1767164840085'
  alias: FrontDoorButton2-Garage
  description: Toggle Garage Door on Front Door Button 2
  triggers:
  - device_id: 3a754aed2f804ba86edfb8bc4aa714ef
    domain: zha
    type: remote_button_short_press
    subtype: button_2
    trigger: device
  conditions: []
  actions:
  - action: cover.stop_cover
    metadata: {}
    data: {}
    target:
      entity_id: cover.garage_door
  mode: single
- id: '1767165043279'
  alias: FrontDoorButton1-LeavingHome
  description: Call Leaving Home to turn everything off and open the garage on Front
    Door Button 1
  triggers:
  - device_id: 3a754aed2f804ba86edfb8bc4aa714ef
    domain: zha
    type: remote_button_short_press
    subtype: button_1
    trigger: device
  conditions: []
  actions:
  - action: script.leaving_home
    metadata: {}
    data: {}
  mode: single
- id: '1767334816619'
  alias: Ping-Down-Notification
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.network_monitor_all
    from: 'on'
  conditions: []
  actions:
  - action: notify.mobile_app_matt_pixel_8_pro
    metadata: {}
    data:
      message: Ping monitoring detected devices down {{now().strftime("%H:%M")}}
  mode: single
- id: '1780926987208'
  alias: Limit Emily Air Con
  description: ''
  use_blueprint:
    path: homeassistant/air_con_limits.yaml
    input:
      climate_entity: climate.emily_air_con
      door_sensors:
      - binary_sensor.emilys_bedroom_emilys_door
  mode: single
- id: '1780926987209'
  alias: Limit Parents Air Con
  description: ''
  use_blueprint:
    path: homeassistant/air_con_limits.yaml
    input:
      climate_entity: climate.parents_air_con
      door_sensors:
      - binary_sensor.parents_bedroom_parents_door
  mode: single
- id: '1781352910573'
  alias: Limit Toby Air Con
  description: ''
  use_blueprint:
    path: homeassistant/air_con_limits.yaml
    input:
      climate_entity: climate.toby_air_con
      door_sensors:
      - binary_sensor.tobys_bedroom_tobys_door
- id: '1781444187793'
  alias: Limit Living Room Air Con
  description: ''
  use_blueprint:
    path: homeassistant/air_con_limits.yaml
    input:
      climate_entity: climate.living_room_air_con
      door_sensors:
      - binary_sensor.living_room_back_stairs_door
      - binary_sensor.kitchen_deck_door
- id: '1782139633606'
  alias: test air con long press
  description: ''
  triggers:
  - trigger: event.received
    target:
      entity_id: event.emilys_bedroom_air_con_board_test_button_1
    options:
      event_type:
      - Long Press
  conditions: []
  actions:
  - action: notify.send_message
    metadata: {}
    data:
      message: test button long press
    target:
      device_id: 87793a362a9ae8561ceeace0d6537f22
  mode: single
