- id: '1643034412279'
  alias: Welcome Lights
  description: ''
  trigger:
  - platform: state
    entity_id: group.family
    to: home
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - service: homeassistant.turn_on
    target:
      entity_id: group.welcome_lights
  - service: notify.admins
    data:
      message: Welcome lights turned on
- id: sensor_lights
  alias: Sensor Lights
  description: Sensor lights combining both sensors and lights
  trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_motion_ac02_iaszone
    to: 'on'
  - platform: state
    entity_id: binary_sensor.front_yard_motion3_motion
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: 0
  action:
  - alias: Turn on the light
    service: light.turn_on
    target:
      entity_id:
      - light.front_yard_sensor_light
      - light.mailbox
    data: {}
  - alias: Wait until there is no motion from either device
    wait_template: '{{ not(is_state(''binary_sensor.lumi_lumi_motion_ac02_iaszone'',
      ''on'')) and not(is_state(''binary_sensor.front_yard_motion3_motion'', ''on''))
      }}'
  - alias: Wait a while longer
    delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - alias: Turn off the light
    service: light.turn_off
    target:
      entity_id:
      - light.front_yard_sensor_light
      - light.mailbox
    data: {}
  mode: restart
