# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: info
  logs:
    homeassistant.components.automation: debug
    homeassistant.core: info
    homeassistant.components.cast: info
    homeassistant.components.cast.media_player: info
    homeassistant.components.recorder: info
    pychromecast: info
    pychromecast.discovery: info
    pychromecast.socket_client: info
    homeassistant.components.zeroconf: info
    custom_components.spotcast: info
    zeroconf: info
    tuya_iot: info
    route53: debug

recorder:
  commit_interval: 30
  purge_keep_days: 31

# Text to speech
tts:
  - platform: google_translate

spotcast:
  sp_dc: !secret spotcast_matt_sp_dc
  sp_key: !secret spotcast_matt_sp_key
  accounts:
    emily:
      sp_dc: !secret spotcast_emily_sp_dc
      sp_key: !secret spotcast_emily_sp_key
    sara:
      sp_dc: !secret spotcast_sara_sp_dc
      sp_key: !secret spotcast_sara_sp_key
    matt:
      sp_dc: !secret spotcast_matt_sp_dc
      sp_key: !secret spotcast_matt_sp_key

panel_custom:
  - name: panel-redirect
    url_path: redirect-supervisor
    sidebar_title: Supervisor
    sidebar_icon: mdi:home-assistant
    module_url: /local/panel-redirect.js
    config:
      target: /hassio/dashboard

person:
  - name: Sara
    id: sara
    user_id: e47941a6895841da96e1afb58282ffdf
    device_trackers:
      - device_tracker.saras_iphone_app

zone:
  - name: Home
    latitude: -27.534078
    longitude: 153.078125
    radius: 65
    icon: mdi:home
  - name: HomeStreet1
    latitude: -27.533366
    longitude: 153.077895
    radius: 40
    icon: mdi:home-minus
  - name: HomeStreet2
    latitude: -27.534767
    longitude: 153.078987
    radius: 65
    icon: mdi:home-minus


route53:
  aws_access_key_id: AKIAZN5CHK57H3XLT2FU
  aws_secret_access_key: !secret aws_access_key
  zone: ZMSGFDQENTCZY
  domain: matt-sullivan.id.au
  records:
    - ha
