# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: info
  logs:
    homeassistant.components.automation: debug
    homeassistant.core: info
    homeassistant.components.cast: info
    homeassistant.components.cast.media_player: info
    homeassistant.components.recorder: info
    pychromecast: info
    pychromecast.discovery: info
    pychromecast.socket_client: info
    homeassistant.components.zeroconf: info
    custom_components.spotcast: info
    zeroconf: info
    tuya_iot: info
    route53: debug

recorder:
  commit_interval: 30
  purge_keep_days: 31

binary_sensor:
  - platform: workday
    country: AU
    province: QLD

# Text to speech
tts:
  - platform: google_translate

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

spotcast:
  sp_dc: !secret spotcast_sp_dc
  sp_key: !secret spotcast_sp_key

panel_custom:
  - name: panel-redirect
    url_path: redirect-supervisor
    sidebar_title: Supervisor
    sidebar_icon: mdi:home-assistant
    module_url: /local/panel-redirect.js
    config:
      target: /hassio/dashboard

person:
  - name: Sara
    id: sara
    user_id: e47941a6895841da96e1afb58282ffdf
    device_trackers:
      - device_tracker.saras_iphone
      - device_tracker.saras_iphone_2

route53:
  aws_access_key_id: AKIAZN5CHK57H3XLT2FU
  aws_secret_access_key: !secret aws_access_key
  zone: ZMSGFDQENTCZY
  domain: matt-sullivan.id.au
  records:
    - ha
