substitutions:
  device_name: lights-toby
  friendly_name: "Toby Lights"
  hotspot_ssid: "Lights-Toby"
  light_name: "Toby Main"
  fan_name: "Toby Fan"

packages:
  common_base: !include packages/common-base.yaml
  mcu: !include packages/bk7231t-wb3s.yaml
  wifi: !include packages/wifi-front-and-hall.yaml
  reboot_common: !include packages/reboot-common.yaml
  lights_and_fan: !include packages/lights-6914ha-series2.yaml
