substitutions:
  device_name: lights-lounge-fan-2
  friendly_name: "Lounge Fan 2"
  hotspot_ssid: "Lounge Fan 2"
  light_name: "Pool Light"
  fan_name: "Lounge Fan 2"

packages:
  common_base: !include packages/common-base.yaml
  mcu: !include packages/bk7231n-cb3s.yaml
  wifi: !include packages/wifi-outside-and-hall.yaml
  reboot_common: !include packages/reboot-common.yaml
  lights_and_fan: !include packages/lights-6914ha-series3.yaml
