substitutions:
  device_name: "lights-ensuite"
  friendly_name: "Ensuite Lights"
  switch_1_name: "Fan"
  switch_2_name: "Light 2"
  switch_3_name: "Light 1"
  hotspot_ssid: "Ensuite Lights Recovery"
  wifi_ssid: !secret wifi_ssid_front

  # Ensuite mix: one fan + two lights
  switch_1_light_internal: true
  switch_1_fan_internal: false
  switch_2_light_internal: false
  switch_2_fan_internal: true
  switch_3_light_internal: false
  switch_3_fan_internal: true

packages:
  common_base: !include packages/common-base.yaml
  mcu: !include packages/bk7231t-wb3s.yaml
  wifi_common: !include packages/wifi-common.yaml
  reboot_common: !include packages/reboot-common.yaml
  lights: !include packages/lights-6903ha-series2.yaml
