substitutions:
  device_name: lights-back-stairs
  friendly_name: "Back Stairs Light"
  hotspot_ssid: "Back Stairs Hotspot"
  wifi_ssid: !secret wifi_ssid
  # 2-way with a dumb remote switch; laundry-door ch3 is a remote button for this lamp
  light_name: "Back Stairs Light"

packages:
  common_base: !include packages/common-base.yaml
  mcu: !include packages/bk7231t-wb3s.yaml
  wifi_common: !include packages/wifi-common.yaml
  reboot_common: !include packages/reboot-common.yaml
  switches: !include packages/lights-6951ha.yaml
  # Target for the "back-stairs" remote button(s)
  link_target: !include
    file: packages/udp-link-target.yaml
    vars:
      link: back-stairs
      light_id: light_1

light:
  - id: !extend light_1
    icon: "mdi:lightbulb"
