substitutions:
  device_name: "lights-bathroom"
  friendly_name: "Bathroom Lights"
  switch_1_name: "Light 1"
  switch_2_name: "Light 2"
  switch_3_name: "Fan"
  hotspot_ssid: "Bathroom Lights Hotspot"
  wifi_ssid: !secret wifi_ssid

  # Bathroom mix: two lights + one fan
  switch_1_light_internal: false
  switch_1_fan_internal: true
  switch_2_light_internal: false
  switch_2_fan_internal: true
  switch_3_light_internal: true
  switch_3_fan_internal: false

packages:
  common_base: !include packages/common-base.yaml
  mcu: !include packages/bk7231t-wb3s.yaml
  wifi_common: !include packages/wifi-common.yaml
  reboot_common: !include packages/reboot-common.yaml
  lights: !include packages/lights-6903ha-series2.yaml