title: Overview
views:
  - title: Kids
    cards:
      - title: Emilys Bedroom
        type: entities
        entities:
          - script.emily_reading_time
          - script.emily_sleep_time
          - light.emily_reading2
          - light.emily_rgb_strip 
          - light.emily_heart
          - cover.emilys_door_blind
          - cover.emilys_side_blind
          - switch.emily_electric_blanket
          - media_player.emilys_bedroom_speaker
          - media_player.spotify_emily
          - media_player.emilys_bedroom_speaker_ma
      - title: Tobys Bedroom
        type: entities
        entities:
          - script.toby_reading_time
          - script.toby_sleep_time
          - script.kids_wakeup
          - light.toby_reading_2
          - light.tobyfroglight
          - light.toby_star_light
          - cover.tobys_front_blind
          - cover.tobys_side_blind
          - switch.toby_electric_blanket
          - media_player.tobys_bedroom_speaker
          - media_player.spotify_toby_sullivan
          - media_player.tobys_bedroom_speaker_ma
      - title: Toby Brushing Duration
        type: statistics-graph
        chart_type: bar
        period: day
        entities:
          - sensor.toby_brushing_duration_am
          - sensor.toby_brushing_duration_pm
        stat_types:
          - max
        days_to_show: 7
        hide_legend: true
  - title: Misc
    cards:
      - title: Misc
        type: entities
        entities:
          # - lock.front_door
          - entity: cover.garage_door
            name: Garage Door
          - sensor.garage_door_state_machine_state
          - binary_sensor.downstairs_laundry_door
          - switch.pool_pump
          # - cover.parents_front_blind
          - cover.parents_front_door_blind
          - cover.parents_side_blind
          - switch.sara_electric_blanket
          # - switch.matt_electric_blanket
          - group.family
          - person.matt
          - person.sara
          - input_boolean.visitors_at_home
          - light.study_downlight
          - light.bin_light
          - light.storage_light
          - input_boolean.music_assistant_no_spotify
          - input_number.toby_start_volume
          - input_number.emily_start_volume
  - title: Camera Overview
    cards:
      - title: Front Yard Camera
        type: picture-entity
        entity: camera.frontyard
        show_name: false
        show_state: false
      - title: Footpath Camera
        type: picture-entity
        entity: camera.footpath
        show_name: false
        show_state: false
      - title: Upstairs Camera
        type: picture-entity
        entity: camera.upstairs
        show_name: false
        show_state: false
      - title: Downstairs Camera
        type: picture-entity
        entity: camera.downstairs
        show_name: false
        show_state: false
  - title: Camera Detail
    type: custom:advanced-camera-card
    cameras:
      - camera_entity: camera.frontyard
      - camera_entity: camera.footpath
      - camera_entity: camera.upstairs
      - camera_entity: camera.downstairs
    status_bar:
      style: outside
      position: top
      popup_seconds: 30
    # profiles:
    #   - casting
    #   - scrubbing
  - title: Batteries
    cards:
      - title: Batteries
        type: entities
        entities:
          - sensor.tobys_front_blind_battery
          - sensor.emilys_door_blind_battery
          - sensor.emilys_side_blind_battery
          - sensor.parents_front_door_blind_battery
          - sensor.parents_side_blind_battery
          - sensor.downstairs_laundry_door_battery
          - sensor.garage_door_closed_sensor_battery
          - sensor.front_yard_motion_stairs_battery
          - sensor.front_yard_mailbox_motion_battery
          - sensor.storage_motion_battery
