title: Overview
views:
  - title: Tab 1
    cards:
      - title: Kids Bedroom
        type: entities
        entities:
          - scene.kids_reading_time
          - script.kids_sleep_time
          - script.kids_wakeup
          - light.kids_long_w
          - light.kids_long_rgb
          - light.kids_short_w
          - light.kids_short_rgb
          - switch.fishtank
          - light.toby_reading
          - light.emily_reading
          - switch.toby_electric_blanket
          - switch.emily_electric_blanket
          - sensor.toby_electric_blanket_power
          - sensor.emily_electric_blanket_power
      - title: Misc
        type: entities
        entities:
          - sensor.pool_ph
          - sensor.pool_temp
          - lock.front_door
          - entity: cover.garage_door
            name: Garage Door
          - group.family
          - input_boolean.visitors_at_home
          - switch.sara_electric_blanket
          
