title: Overview
views:
  - title: Tab 1
    cards:
      - title: Emilys Bedroom
        type: entities
        entities:
          - light.emilys_bedroom_light
          - light.emily_bed
          - light.emily_reading2
          - light.emily_rgb_strip 
          - light.emily_white_strip 
          - script.emily_reading_time
          - script.emily_sleep_time
          - media_player.googlehome1978
          - media_player.spotify_emily
      - title: Tobys Bedroom
        type: entities
        entities:
          - script.toby_reading_time
          - script.toby_sleep_time
          - script.kids_wakeup
          - light.kids_short_w
          - light.kids_short_rgb
          - light.toby_reading_2
          - light.tobyfroglight
          - switch.toby_electric_blanket
          - cover.toby_front_blind
          - media_player.emilys_room_speaker
          - media_player.spotify_matt_sullivan
      - title: Misc
        type: entities
        entities:
          - sensor.pool_ph
          - sensor.pool_temp
          # - lock.front_door
          - entity: cover.garage_door
            name: Garage Door
          - group.family
          - input_boolean.visitors_at_home
          # - switch.sara_electric_blanket
