title: Overview
views:
  - title: Tab 1
    cards:
      - title: Emilys Bedroom
        type: entities
        entities:
          - light.emilys_bedroom_light
          - script.emily_reading_time
          - script.emily_night_music
          - script.emily_sleep_time
          - media_player.googlehome1978
          - media_player.spotify_emily
      - title: Tobys Bedroom
        type: entities
        entities:
          - scene.toby_reading_time
          - script.toby_sleep_time
          - script.toby_broncos_music
          - script.kids_wakeup
          - light.kids_long_w
          - light.kids_long_rgb
          - light.kids_short_w
          - light.kids_short_rgb
          - light.toby_reading
          - light.emily_reading
          - media_player.emilys_room_speaker
          - media_player.spotify_matt_sullivan
      - title: Misc
        type: entities
        entities:
          - sensor.pool_ph
          - sensor.pool_temp
          - lock.front_door
          - entity: cover.garage_door
            name: Garage Door
          - group.family
          - input_boolean.visitors_at_home
          - switch.sara_electric_blanket
