title: Overview
views:
  - title: Tab 1
    cards:
      - title: Emilys Bedroom
        type: entities
        entities:
          - script.emily_reading_time
          - script.emily_sleep_time
          - light.emily_reading2
          - light.emily_rgb_strip 
          - light.emily_heart
          - cover.emilys_door_blind
          - cover.emilys_side_blind
          - media_player.googlehome1978
          - media_player.spotify_emily
      - title: Tobys Bedroom
        type: entities
        entities:
          - script.toby_reading_time
          - script.toby_sleep_time
          - script.kids_wakeup
          - light.toby_reading_2
          - light.tobyfroglight
          - light.toby_star_light
          - cover.tobys_front_blind
          - cover.tobys_side_blind
          - media_player.emilys_room_speaker
          - media_player.spotify_toby_sullivan
      - title: Misc
        type: entities
        entities:
          - lock.front_door
          - entity: cover.garage_door
            name: Garage Door
          - sensor.garage_door_state_machine_state
          - binary_sensor.downstairs_laundry_door
          - switch.xmas_tree
          - cover.parents_front_blind
          - cover.parents_front_door_blind
          - cover.parents_side_blind
          - group.family
          - person.matt
          - person.sara
          - input_boolean.visitors_at_home
          - light.bin_light
          # - switch.sara_electric_blanket
      - title: Front Entry Camera
        type: picture-entity
        entity: camera.front_entry_camera
        show_name: false
        show_state: false
      - title: Footpath Camera
        type: picture-entity
        entity: camera.footpath_camera_2
        show_name: false
        show_state: false
      - title: Batteries
        type: entities
        entities:
          - sensor.tobys_front_blind_battery
          - sensor.emilys_door_blind_battery
          - sensor.emilys_side_blind_battery
          - sensor.parents_front_door_blind_battery
          - sensor.parents_side_blind_battery
          - sensor.downstairs_laundry_door_battery
          - sensor.garage_door_closed_sensor_battery
          - entity: sensor.lumi_lumi_motion_ac02_battery
            name: Sensor Light 1 Battery
          - entity: sensor.front_yard_motion3_battery
            name: Sensor Light 2 Battery
