title: Overview
views:
  - title: Kids
    cards:
      - title: Emilys Bedroom
        type: entities
        entities:
          - script.emily_reading_time
          - script.emily_sleep_time
          - light.emily_reading2
          - light.emily_rgb_strip 
          - light.emily_heart
          - cover.emilys_door_blind
          - cover.emilys_side_blind
          - switch.emily_electric_blanket
          - climate.emily_air_con
          - media_player.emilys_bedroom_speaker
          - media_player.spotify_emily
          - media_player.emilys_bedroom_speaker_ma
      - title: Tobys Bedroom
        type: entities
        entities:
          - script.toby_reading_time
          - script.toby_sleep_time
          - script.kids_wakeup
          - light.toby_reading_2
          - light.tobyfroglight
          - light.toby_star_light
          - cover.tobys_front_blind
          - cover.tobys_side_blind
          - switch.toby_electric_blanket
          - media_player.tobys_bedroom_speaker
          - media_player.spotify_toby_sullivan
          - media_player.tobys_bedroom_speaker_ma
      - title: Toby Brushing Duration
        type: statistics-graph
        chart_type: bar
        period: day
        entities:
          - sensor.toby_brushing_duration_am
          - sensor.toby_brushing_duration_pm
        stat_types:
          - max
        days_to_show: 7
        hide_legend: true
  - title: Misc
    cards:
      - title: Parents
        type: entities
        entities:
          # - cover.parents_front_blind
          - cover.parents_front_door_blind
          - cover.parents_side_blind
          - switch.sara_electric_blanket
          - switch.matt_electric_blanket
          - climate.parents_air_con
      - title: Misc
        type: entities
        entities:
          # - lock.front_door
          - entity: cover.garage_door
            name: Garage Door
          - binary_sensor.downstairs_laundry_door
          - binary_sensor.downstairs_deck_door
          - switch.pool_pump
          - light.study_downlight
          - light.bin_light
          - light.storage_light
          - sensor.garage_door_state_machine_state
      - title: Config
        type: entities
        entities:
          - input_boolean.visitors_at_home
          - input_boolean.music_assistant_no_spotify
          - input_number.toby_start_volume
          - input_number.emily_start_volume
          - input_number.aircon_max_heat_temp
          - input_number.aircon_min_cool_temp
          - group.family
          - person.matt
          - person.sara
  - title: Camera Overview
    cards:
      - title: Front Yard Camera
        type: picture-entity
        entity: camera.frontyard
        show_name: false
        show_state: false
      - title: Footpath Camera
        type: picture-entity
        entity: camera.footpath
        show_name: false
        show_state: false
      - title: Upstairs Camera
        type: picture-entity
        entity: camera.upstairs
        show_name: false
        show_state: false
      - title: Downstairs Camera
        type: picture-entity
        entity: camera.downstairs
        show_name: false
        show_state: false
  - title: Camera Detail
    type: custom:advanced-camera-card
    cameras:
      - camera_entity: camera.frontyard
      - camera_entity: camera.footpath
      - camera_entity: camera.upstairs
      - camera_entity: camera.downstairs
    status_bar:
      style: outside
      position: top
      popup_seconds: 30
    # profiles:
    #   - casting
    #   - scrubbing
  - title: Batteries
    cards:
      - title: Batteries
        type: entities
        entities:
          - sensor.tobys_front_blind_battery
          - sensor.tobys_side_blind_battery
          - sensor.emilys_door_blind_battery
          - sensor.emilys_side_blind_battery
          - sensor.parents_front_door_blind_battery
          - sensor.parents_side_blind_battery
          - sensor.downstairs_laundry_door_battery
          - sensor.downstairs_deck_door_battery
          - sensor.garage_door_closed_sensor_battery
          - sensor.front_yard_motion_stairs_battery
          - sensor.front_yard_mailbox_motion_battery
          - sensor.storage_motion_battery
  - title: Network Monitor
    cards:
      - title: Overview
        type: entities
        entities:
          - binary_sensor.network_monitor_all
          - binary_sensor.network_monitor_front
          - binary_sensor.network_monitor_hall
          - binary_sensor.network_monitor_outside
          - binary_sensor.network_monitor_upstream
          - sensor.apfront_clients
          - sensor.apupstairshallway_clients
          - sensor.ap_outside2_clients
      - title: Front AP
        type: entities
        entities:
          - binary_sensor.lights_ensuite_ping
          - device_tracker.lights_ensuitelocal_is_home
          - binary_sensor.lights_ensuitelocal_is_present
          - device_tracker.lights_ensuite
          - binary_sensor.lights_entry_ping
          - binary_sensor.lights_toby_ping
          - binary_sensor.lights_parents_ping
          - binary_sensor.wemosd1_garage_ping
      - title: Hall AP
        type: entities
        entities:
          - binary_sensor.bluetooth_proxy_2_ping
          - device_tracker.bluetooth_proxy_2_is_home
          - binary_sensor.bluetooth_proxy_2_is_present
          - device_tracker.bluetooth_proxy_2
          - binary_sensor.toothbrush_monitor_2_ping
          - device_tracker.toothbrush_monitor_2_is_home
          - binary_sensor.toothbrush_monitor_2_is_present
          - device_tracker.toothbrush_monitor_2
          - binary_sensor.lounge_google_tv_ping
          - binary_sensor.emilys_tv_ping
      - title: Outside AP
        type: entities
        entities:
          - binary_sensor.lights_bathroom_ping
          - binary_sensor.lights_kitchen_ping
          - binary_sensor.google_home_ping
      - title: Upstream
        type: entities
        entities:
          - binary_sensor.unifi_router_ping
          - binary_sensor.google_dns_ping
      - title: History
        type: history-graph
        hours_to_show: 48
        entities:
          - binary_sensor.network_monitor_all
          - binary_sensor.network_monitor_front
          - binary_sensor.network_monitor_hall
          - binary_sensor.network_monitor_outside
          - binary_sensor.lights_ensuite_ping
          - binary_sensor.lights_entry_ping
          - binary_sensor.lights_toby_ping
          - binary_sensor.lights_parents_ping
          - binary_sensor.wemosd1_garage_ping
          - binary_sensor.bluetooth_proxy_2_ping
          - binary_sensor.toothbrush_monitor_2_ping
          - binary_sensor.lounge_google_tv_ping
          - binary_sensor.emilys_tv_ping
          - binary_sensor.lights_bathroom_ping
          - binary_sensor.lights_kitchen_ping
          - binary_sensor.google_home_ping
          - binary_sensor.unifi_router_ping
          - binary_sensor.google_dns_ping
  - title: Schedules
    cards:
      - title: Climate
        type: custom:scheduler-card
        include:
          - light
          - climate
          - cover
          - script
        display_options:
          secondary_info:
            - time
            - days
            - additional-tasks
        show_header_toggle: true
        show_toggle_switches: true
        tags: climate
      - title: Wake Up Alarms
        type: custom:scheduler-card
        include:
          - light
          - climate
          - cover
          - script
        display_options:
          secondary_info:
            - time
            - days
            - additional-tasks
        show_header_toggle: true
        show_toggle_switches: true
        tags: alarm
        discover_existing: false