title: Tobys Bedroom
kiosk_mode:
  kiosk: true
views:
  - type: sections
    sections:
      - type: grid
        cards:
          - type: tile
            entity: light.tobys_bedroom_toby_light_bar
            name: Light Bar
            hide_state: true
            vertical: false
            features:
              - type: light-color-favorites
              - type: light-brightness
            features_position: bottom
          - type: tile
            entity: light.tobys_bedroom_toby_reading_light
            name: Reading Light
            vertical: false
            features:
              - type: light-brightness
            features_position: bottom
          - type: tile
            entity: light.tobyfroglight
            name: Frog Light
            features:
              - type: toggle
      - type: grid
        cards:
          - type: tile
            entity: cover.tobys_front_blind
            features:
              - type: "cover-open-close"
          - type: tile
            entity: cover.tobys_side_blind
            features:
              - type: "cover-open-close"
      - type: grid
        cards:
          - type: entities
            entities:
              - media_player.tobys_bedroom_speaker_ma
          - type: tile
            entity: media_player.tobys_bedroom_speaker_ma
            features:
              - type: "media-player-volume-buttons"
      - type: grid
        cards:
          - type: tile
            entity: switch.tobys_bedroom_toby_electric_blanket
            features:
              - type: toggle
          - type: tile
            entity: fan.toby
            features:
              - type: fan-speed
      - type: grid
        cards:
          - type: thermostat
            entity: climate.toby_air_con
            show_current_as_primary: false
            name: Air Con
            features:
              - type: climate-hvac-modes
                hvac_modes:
                  - "off"
                  - fan_only
                  - cool
                  - heat
              - type: climate-fan-modes
                style: dropdown
      - type: grid
        cards:
          - type: entities
            entities:
              - script.toby_reading_time
              - script.toby_sleep_time
    cards: []
    max_columns: 2
    dense_section_placement: true
