substitutions:
  device_name: lights-emily2
  friendly_name: "Emily Lights"
  deviceicon: "mdi:light-recessed"
  hotspot_ssid: "Emily Lights Hotspot"
  wifi_ssid: !secret wifi_ssid

packages:
  common_base: !include packages/common-base.yaml
  bk72xx_overlay: !include packages/bk72xx-overlay.yaml
  wifi_common: !include packages/wifi-common.yaml

status_led:
  pin:
    number: P24
    inverted: true

uart:
  rx_pin: P10
  tx_pin: P11
  baud_rate: 9600

# Register the Tuya MCU connection
tuya:

# light settings
light:
  - platform: "tuya"
    name: "${friendly_name}"
    # dimmers current value
    dimmer_datapoint: 2
    # dimmer on/off
    switch_datapoint: 1
    min_value_datapoint: 3
    min_value: 0
    max_value: 1000

switch:
  - platform: restart
    name: "Reboot"
