uart:
  - id: debug_uart
    tx_pin: GPIO16
    rx_pin: GPIO17
    baud_rate: 115200
  - id: uartbus1
    tx_pin: GPIO18
    rx_pin: GPIO19
    baud_rate: 9600
    parity: EVEN

climate:
  - platform: panasonic_ac
    id: climate_entity
    name: None
    # For CZ-TACG1
    type: cnt
    uart_id: uartbus1

    # For DNSK-P11
    # type: wlan

    horizontal_swing_select:
      name: Horizontal Swing Mode
    vertical_swing_select:
      name: Vertical Swing Mode
    outside_temperature:
      name: Outside Temperature

    # Enable as needed
    eco_switch:
      name: Panasonic AC Eco Switch
    # econavi_switch:
    #   name: Panasonic AC Econavi Switch
    # nanoex_switch:
    #   name: Panasonic AC NanoeX Switch
    mild_dry_switch:
      name: Panasonic AC Mild Dry Switch
    # current_power_consumption:
    #   name: Panasonic AC Power Consumption

    # Adapt according to your measurements
    # current_temperature_offset: 0
    # outside_temperature_offset: 0

    # Useful when the ac does not report a current temperature (CZ-TACG1 only)
    # current_temperature_sensor: temperature_sensor_id