wifi:
  networks:
    - ssid: !secret wifi_ssid_front
      password: !secret wifi_password
    - ssid: !secret wifi_ssid_hall
      password: !secret wifi_password
  reboot_timeout: 1h

  ap:
    ssid: "${hotspot_ssid}"
    password: !secret fallback_password