sensor:
  # Weather prediction
  - platform: openweathermap
    api_key: !secret openweathermap_api_key
    name: Exterior
    language: es
    monitored_conditions:
      - weather
      - temperature
      - wind_speed
      - humidity
      - pressure
      - clouds
      - rain
    scan_interval: 600

  - platform: time_date
    display_options:
      - 'time'
