input_number:
  pool_capacity:
    name: Pool capacity (m3)
    min: 5
    max: 100
    unit_of_measurement: m3
    icon: mdi:water-pump

input_boolean:
  factory_started:
    name: Factory config started
    icon: mdi:auto-fix

automation:
- alias: Pool settings factory started
  id: '1559149839000'
  initial_state: true
  trigger:
    platform: homeassistant
    event: start
  condition: 
    condition: state 
    entity_id: input_boolean.factory_started
    state: 'off'
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.factory_started
  - service: input_number.set_value
    data_template:
      entity_id: input_number.pool_capacity
      value: 50
  - service: input_number.set_value
    data_template:
      entity_id: input_number.fc_target
      value: 1.5
  - service: input_number.set_value
    data_template:
      entity_id: input_number.e_fc_adjust
      value: 0
  - service: input_number.set_value
    data_template:
      entity_id: input_number.ph_target
      value: 7.2
  - service: input_number.set_value
    data_template:
      entity_id: input_number.muriatic_tank
      value: 10
  - service: input_number.set_value
    data_template:
      entity_id: input_number.muriatic_concentration
      value: 20
  - service: input_number.set_value
    data_template:
      entity_id: input_number.muriatic_speed
      value: 25
