template:
  - device_tracker:
      - name: Visitors Presence
        unique_id: visitors_presence
        in_zones: "{{ ['zone.home'] if is_state('input_boolean.visitors_at_home', 'on') else [] }}"

input_boolean:
  visitors_at_home:
    name: Visitors At Home

person:
  - name: Visitors
    id: vistors
    device_trackers:
      - device_tracker.visitors_presence

automation:
  - id: visitors_reset_when_person_arrives
    alias: Reset visitors when person arrives home
    trigger:
      - platform: state
        entity_id:
          - person.matt
          - person.sara
        from: "not_home"
        to: "home"
    condition:
      - condition: state
        entity_id: input_boolean.visitors_at_home
        state: "on"
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.visitors_at_home
