substitutions:
  device_name: air-con-emily
  friendly_name: "Emily Air Con"
  hotspot_ssid: "Emily Air Con Hotspot"

external_components:
  - source: github://DomiStyle/esphome-panasonic-ac

packages:
  common_base: !include packages/common-base.yaml
  esp32_c6_idf: !include packages/esp32-c6-idf.yaml
  wifi_front_and_hall: !include packages/wifi-front-and-hall.yaml
  air_con_common: !include packages/air-con-common.yaml
  air_con_panasonic: !include packages/air-con-panasonic.yaml

preferences:
  flash_write_interval: never