substitutions:
  device_name: air-con-board-test
  friendly_name: "Air Con Board Test"
  hotspot_ssid: "Air Con Board Test"

external_components:
  - source: github://DomiStyle/esphome-panasonic-ac

packages:
  common_base: !include packages/common-base.yaml
  esp32_c6_idf: !include packages/esp32-c6-idf.yaml
  wifi_front_and_hall: !include packages/wifi-front-and-hall.yaml

logger:
  level: VERBOSE

light:
  - platform: status_led
    name: "Status LED"
    pin:
      number: GPIO8
      inverted: True
      ignore_strapping_warning: true

uart:
  - id: debug_uart
    tx_pin: GPIO16
    rx_pin: GPIO17
    baud_rate: 9600
    debug:
      direction: BOTH
      dummy_receiver: true
      debug_prefix: "[UARTPROG] "
      after:
        delimiter: "\n"
      sequence:
        - lambda: UARTDebug::log_string(direction, bytes, debug_prefix);
  - id: uartbus1
    tx_pin: GPIO18
    rx_pin: GPIO19
    baud_rate: 9600
    debug:
      direction: BOTH
      dummy_receiver: true
      debug_prefix: "[UARTCOMMS] "
      after:
        delimiter: "\n"
      sequence:
        - lambda: UARTDebug::log_string(direction, bytes, debug_prefix);



interval:
  - interval: 1s
    then:
      - logger.log: "Sending test data to UARTs"
      - uart.write:
          id: debug_uart
          data: "hello 0123456789 0123456789 0123456789 0123456789 0123456789\n"
      - uart.write:
          id: uartbus1
          data: "hello 0123456789 0123456789 0123456789 0123456789 0123456789\n"
      - lambda: |-
          id(debug_uart).flush();
          id(uartbus1).flush();

text_sensor:
  - platform: version
    name: "Firmware Version"
    entity_category: diagnostic
