substitutions:
  device_name: air-con-board-test
  friendly_name: "Air Con Board Test"
  hotspot_ssid: "Air Con Board Test"

external_components:
  - source: github://DomiStyle/esphome-panasonic-ac

packages:
  common_base: !include packages/common-base.yaml
  esp32_c6_idf: !include packages/esp32-c6-idf.yaml
  wifi_front_and_hall: !include packages/wifi-front-and-hall.yaml

logger:
  level: VERBOSE

light:
  - platform: status_led
    name: "Status LED"
    pin:
      number: GPIO8
      inverted: True
      ignore_strapping_warning: true

uart:
  - id: prog_uart
    tx_pin: GPIO16
    rx_pin: GPIO17
    baud_rate: 115200

  # - id: comms_uart
  #   tx_pin: GPIO18
  #   rx_pin: GPIO19
  #   baud_rate: 115200

i2c:
  sda: GPIO6
  scl: GPIO7
  scan: true

ads1115:
  - address: 0x48

one_wire:
  - platform: gpio
    pin: GPIO15

event:
  - platform: template
    id: button_1
    name: Button 1
    device_class: "button"
    event_types:
      - "Long Press"

binary_sensor:
  - platform: gpio
    name: "Boot"
    pin:
      number: GPIO9
      inverted: true
    on_multi_click:
      - timing:
          - on for at least 1s
        then:
          - event.trigger:
              id: button_1
              event_type: "Long Press"

  - platform: gpio
    name: "5V #1"
    pin:
      number: GPIO18
      mode: INPUT_OUTPUT_OPEN_DRAIN
      allow_other_uses: true

  - platform: gpio
    name: "5V #2"
    pin:
      number: GPIO19
      mode: INPUT_OUTPUT_OPEN_DRAIN
      allow_other_uses: true

  - platform: gpio
    name: "5V #3"
    pin:
      number: GPIO20
      mode: INPUT_OUTPUT_OPEN_DRAIN
      allow_other_uses: true

  - platform: gpio
    name: "24V #1"
    pin:
      number: GPIO21
      inverted: true

  - platform: gpio
    name: "24V #2"
    pin:
      number: GPIO22
      inverted: true

  - platform: gpio
    name: "24V #3"
    pin:
      number: GPIO23
      inverted: true

switch:
  - platform: gpio
    name: "5V #1"
    pin:
      number: GPIO18
      mode: INPUT_OUTPUT_OPEN_DRAIN
      allow_other_uses: true

  - platform: gpio
    name: "5V #2"
    pin:
      number: GPIO19
      mode: INPUT_OUTPUT_OPEN_DRAIN
      allow_other_uses: true

  - platform: gpio
    name: "5V #3"
    pin:
      number: GPIO20
      mode: INPUT_OUTPUT_OPEN_DRAIN
      allow_other_uses: true

  - platform: gpio
    name: "24V #1"
    pin:
      number: GPIO2
      inverted: true

  - platform: gpio
    name: "24V #2"
    pin:
      number: GPIO3
      inverted: true

sensor:
  - platform: pulse_counter
    pin:
      number: GPIO20
      mode: INPUT_OUTPUT_OPEN_DRAIN
      allow_other_uses: true
    name: "Pulse Counter"

  - platform: dallas_temp
    name: Temperature
    update_interval: 60s

  - platform: ads1115
    name: "Analog Input 1"
    multiplexer: 'A0_GND'
    gain: 2.048
    update_interval: 60s

  - platform: ads1115
    name: "Analog Input 2"
    multiplexer: 'A1_GND'
    gain: 2.048
    update_interval: 60s

