# Testing DAIKIN IR interface on ESP8285 IR transceiver board
substitutions:
  device_name: air-con-test
  friendly_name: Test Air Con
  hotspot_ssid: "Test Air Con Hotspot"
  wifi_ssid: !secret wifi_ssid

packages:
  common_base: !include packages/common-base.yaml
  esp8266_esp8285: !include packages/esp8266-esp8285.yaml
  wifi_common: !include packages/wifi-common.yaml

remote_receiver:
  pin:
    number: GPIO14
    inverted: true
  dump: all
  tolerance: 55%
  id: ir_receiver
  idle: 5ms # required

remote_transmitter:
  pin: GPIO4
  carrier_duty_percent: 50%

button:
  - platform: template
    name: "Turn Off"
    on_press:
      - climate.control:
          id: climate_entity
          mode: "OFF"

  - platform: template
    name: "Turn On"
    on_press:
      then:
        - climate.control:
            id: climate_entity
            mode: "COOL"
            target_temperature: 23
            fan_mode: MEDIUM
            swing_mode: BOTH

climate:
  - platform: daikin
    id: climate_entity
    name: None
    receiver_id: ir_receiver
    supports_cool: true
    supports_heat: true
