substitutions:
  name: "bluetooth-proxy-1"
  friendly_name: Bluetooth Proxy 1
esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

api:
  reboot_timeout: 24h
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    id: ota_esphome

wifi:
  ssid: !secret wifi_ssid_hall
  password: !secret wifi_password
  reboot_timeout: 1h

## ------------------ ##
##    Generic Sensors ##
## ------------------ ##
sensor:
  - platform: wifi_signal
    name: "Wifi Signal Strength"
    update_interval: 60s
  
  - platform: uptime
    name: "Uptime"
    filters:
      - lambda: return x / 86400.0;
    unit_of_measurement: "d"
    accuracy_decimals: 1
    update_interval: 5min

switch:
  - platform: restart
    id: restart_device
    name: "Reboot"

bluetooth_proxy:
  active: true

esp32_ble_tracker:
  scan_parameters:
    # We currently use the defaults to ensure Bluetooth
    # can co-exist with WiFi In the future we may be able to
    # enable the built-in coexistence logic in ESP-IDF
    active: true
