substitutions:
  device_name: gpo-switch-13
  friendly_name: "Smart Plug 13"
  hotspot_ssid: "Smart Plug 13"

packages:
  common_base: !include packages/common-base.yaml
  wifi: !include packages/wifi-outside-and-hall.yaml
  reboot_common: !include packages/reboot-common.yaml

# From https://devices.esphome.io/devices/arlec-pc191ha-plug/

bk72xx:
  board: cb2s
  framework:
    version: dev

# PC191HA basic switch operation - button, relay and LED
#
# button is momentary on - shows "off" in HA except for the moment the button is being pressed
# LED should have same on/off state as the relay.
# there is also a wifi_LED, but it is not seen from outside the case

binary_sensor: # the button
  - platform: gpio
    pin:
      number: P11
      inverted: true
    name: Button
    id: button
    disabled_by_default: true
    # when button is pressed, toggle the switch on/off
    on_press:
      then:
        - switch.toggle: relay

switch: # the relay
  - platform: gpio
    pin: P8
    # Specify a blank name so home assistant uses the main device name
    name: None
    id: relay
    restore_mode: always off # default when power is turned on
    icon: mdi:power-socket-au
    # synchronise the LED with the relay
    on_turn_on:
      then:
        - output.turn_on: button_led
    on_turn_off:
      then:
        - output.turn_off: button_led

output: # the light in the button
  - platform: gpio
    id: button_led
    pin: P26

#
# PC191HA sensors - power monitoring and wifi signal
#
sensor:
    # PC191HA includes a BL0937 chip for measuring power consumption
    #     and BL0937 is a variation of hlw8012, but using inverted SEL pin functionality
  - platform: hlw8012
    model: BL0937 # note that the model must be specified to use special calculation parameters
    sel_pin: # I believe that cf_pin reports either Voltage or Current depending on this select pin
      inverted: true # determine whether true reports Voltage
      number: P24
    cf_pin: # current or voltage (ele_pin: 7)
      inverted: true # the logic of BL0937 is opposite from HLW8012
      number: P7
    cf1_pin: #  Power (vi_pin: 8)
      inverted: true # the logic of BL0937 is opposite from HLW8012
      number: P6

    # Measure and report every 5 seconds
    update_interval: 5s 

    # PC191HA measures and returns Voltage OR Current according to the value of sel_pin,
    #   but it can change the value of sel_pin periodically
    initial_mode: "VOLTAGE" # reports VOLTAGE or CURRENT
    change_mode_every:
      4 # how many times to report before swapping between
      #   reporting Voltage or Current. Note that the first value reported should be ignored as inaccurate

    # Adjust according to the actual resistor values on board to calibrate the specific unit
    voltage_divider: 775 # LOWER VALUE GIVES LOWER VOLTAGE
    current_resistor: 0.0009 # HIGHER VALUE GIVES LOWER WATTAGE

    #
    # how the power monitoring values are returned to ESPHome
    #

    voltage:
      name: Voltage
      id: voltage
      unit_of_measurement: V
      accuracy_decimals: 1
      filters:
        - skip_initial: 2
    power:
      name: Power
      id: power
      unit_of_measurement: W
      accuracy_decimals: 2
      filters:
        - skip_initial: 2

    # power should simply be current x voltage -- except that the pc191ha doesn't follow that formula.
    # Setting current_resistor to give an accurate Amperage does NOT also give the correct Wattage
    # so here I calculate current from power and voltage

  - platform: template
    name: Current
    id: current
    unit_of_measurement: A
    accuracy_decimals: 2
    lambda: |-
      return (id(power).state / id(voltage).state);
    filters:
      - skip_initial: 2
