esphome:
  name: h801-emily
  platform: ESP8266
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "6e6c92844da208f21c6ef965d2939506"

wifi:
  ssid: "MattAndSara"
  password: !secret wifi_password 

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "H801-Emily Fallback Hotspot"
    password: "VfSD0MqYCNLg"

captive_portal:

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Emily H801"
    update_interval: 60s

#RGBWarm
output:
  - platform: esp8266_pwm
    pin: 12
    frequency: 1000 Hz
    id: pwm_b
  - platform: esp8266_pwm
    pin: 13
    frequency: 1000 Hz
    id: pwm_g
  - platform: esp8266_pwm
    pin: 15
    frequency: 1000 Hz
    id: pwm_r
  - platform: esp8266_pwm
    pin: 14
    frequency: 1000 Hz
    id: pwm_w1
  - platform: esp8266_pwm
    pin: 4
    frequency: 1000 Hz
    id: pwm_w2
light:
  - platform: rgb
    name: "kids_short_rgb"
    id: "kids_short_rgb"
    red: pwm_r
    green: pwm_g
    blue: pwm_b
  - platform: monochromatic
    name: "kids_short_w"
    id: "kids_short_w"
    output: pwm_w1
  - platform: monochromatic
    name: "emily_reading"
    id: "emily_reading"
    output: pwm_w2

binary_sensor:
  - platform: gpio
    name: "emily_reading_button"
    id: "emily_reading_button"
    pin:
      number: 3
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
    on_press:
      then:
        - light.toggle: emily_reading
