substitutions:
  device_name: h801-toby
  friendly_name: "Toby Reading Light"
  hotspot_ssid: "TobyReadingLight"
  wifi_ssid: !secret wifi_ssid_upstairs

packages:
  common_base: !include packages/common-base.yaml
  esp8266_overlay: !include packages/esp8266-overlay.yaml
  wifi_common: !include packages/wifi-common.yaml
  reboot_common: !include packages/reboot-common.yaml

#RGBWarm
output:
  - platform: esp8266_pwm
    pin: 12
    frequency: 1000 Hz
    id: pwm_b
  - platform: esp8266_pwm
    pin: 13
    frequency: 1000 Hz
    id: pwm_g
  - platform: esp8266_pwm
    pin: 15
    frequency: 1000 Hz
    id: pwm_r
  - platform: esp8266_pwm
    pin: 14
    frequency: 1000 Hz
    id: pwm_w1
  - platform: esp8266_pwm
    pin: 4
    frequency: 1000 Hz
    id: pwm_w2
light:
  - platform: rgb
    name: "kids_short_rgb"
    id: "kids_short_rgb"
    red: pwm_r
    green: pwm_g
    blue: pwm_b
  - platform: monochromatic
    name: "kids_short_w"
    id: "kids_short_w"
    output: pwm_w1
  - platform: monochromatic
    name: "toby_reading"
    id: "toby_reading"
    output: pwm_w2

binary_sensor:
  - platform: gpio
    name: "toby_reading_button"
    id: "toby_reading_button"
    pin:
      number: 3
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
    on_press:
      then:
        - light.toggle: toby_reading
