substitutions:
  device_name: h801-toby
  friendly_name: "Toby Reading Light"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp8266:
  board: esp01_1m

# Enable logging
logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid_upstairs
  password: !secret wifi_password 
  reboot_timeout: 1h

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "TobyReadingLight"
    password: !secret fallback_password

captive_portal:

# Enable Home Assistant API
api:
  reboot_timeout: 24h

ota:
  platform: esphome
  password: !secret ota_password

# The web_server & sensor components can be removed without affecting core functionaility.
web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Toby H801"
    update_interval: 60s

#RGBWarm
output:
  - platform: esp8266_pwm
    pin: 12
    frequency: 1000 Hz
    id: pwm_b
  - platform: esp8266_pwm
    pin: 13
    frequency: 1000 Hz
    id: pwm_g
  - platform: esp8266_pwm
    pin: 15
    frequency: 1000 Hz
    id: pwm_r
  - platform: esp8266_pwm
    pin: 14
    frequency: 1000 Hz
    id: pwm_w1
  - platform: esp8266_pwm
    pin: 4
    frequency: 1000 Hz
    id: pwm_w2
light:
  - platform: rgb
    name: "kids_short_rgb"
    id: "kids_short_rgb"
    red: pwm_r
    green: pwm_g
    blue: pwm_b
  - platform: monochromatic
    name: "kids_short_w"
    id: "kids_short_w"
    output: pwm_w1
  - platform: monochromatic
    name: "toby_reading"
    id: "toby_reading"
    output: pwm_w2

binary_sensor:
  - platform: gpio
    name: "toby_reading_button"
    id: "toby_reading_button"
    pin:
      number: 3
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
    on_press:
      then:
        - light.toggle: toby_reading
