esphome:
  name: h801-toby
  platform: ESP8266
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "6c91cd96dd82e4ca3816fbde0a5fc90a"

wifi:
  ssid: "MattAndSara"
  password:  !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "H801-Toby Fallback Hotspot"
    password: "WCGgF0GzYYdw"

captive_portal:

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Toby H801"
    update_interval: 60s

#RGBWarm
output:
  - platform: esp8266_pwm
    pin: 12
    frequency: 1000 Hz
    id: pwm_b
  - platform: esp8266_pwm
    pin: 13
    frequency: 1000 Hz
    id: pwm_g
  - platform: esp8266_pwm
    pin: 15
    frequency: 1000 Hz
    id: pwm_r
  - platform: esp8266_pwm
    pin: 14
    frequency: 1000 Hz
    id: pwm_w1
  - platform: esp8266_pwm
    pin: 4
    frequency: 1000 Hz
    id: pwm_w2
light:
  - platform: rgb
    name: "kids_long_rgb"
    id: "kids_long_rgb"
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    effects:
      - pulse:
      - random:
      - strobe:
          name: Strobe
          colors:
            - state: true
              red: 100%
              green: 0%
              blue: 0%
              duration: 500ms
            - state: false
              duration: 250ms
            - state: true
              red: 100%
              green: 100%
              blue: 0%
              duration: 500ms
            - state: false
              duration: 250ms
            - state: true
              red: 0%
              green: 100%
              blue: 0%
              duration: 500ms
            - state: false
              duration: 250ms
            - state: true
              red: 0%
              green: 100%
              blue: 100%
              duration: 500ms
            - state: false
              duration: 250ms
            - state: true
              red: 0%
              green: 0%
              blue: 100%
              duration: 500ms
            - state: false
              duration: 250ms
            - state: true
              red: 100%
              green: 0%
              blue: 100%
              duration: 500ms
            - state: false
              duration: 250ms
            - state: true
              red: 100%
              green: 0%
              blue: 0%
              duration: 500ms
            - state: false
              duration: 250ms
  - platform: monochromatic
    name: "kids_long_w"
    id: "kids_long_w"
    output: pwm_w1
  - platform: monochromatic
    name: "toby_reading"
    id: "toby_reading"
    output: pwm_w2
          
binary_sensor:
  - platform: gpio
    name: "toby_reading_button"
    id: "toby_reading_button"
    pin:
      number: 3
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
    on_press:
      then:
        - light.toggle: toby_reading
