esphome:
  name: h801-emily2
  platform: ESP8266
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 24h

ota:
  password: "6c91cd96dd82e4ca3816fbde0a5fc90a"

wifi:
  ssid: "MattAndSara"
  password:  !secret wifi_password
  reboot_timeout: 1h

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "H801-Emily2 Fallback Hotspot"
    password: "WCGgF0GzYYdw"

captive_portal:

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Emily2 H801"
    update_interval: 60s

#RGBWarm
output:
  - platform: esp8266_pwm
    pin: 12
    frequency: 1000 Hz
    id: pwm_b
  - platform: esp8266_pwm
    pin: 13
    frequency: 1000 Hz
    id: pwm_r
  - platform: esp8266_pwm
    pin: 15
    frequency: 1000 Hz
    id: pwm_g
  - platform: esp8266_pwm
    pin: 14
    frequency: 1000 Hz
    id: pwm_w1
  - platform: esp8266_pwm
    pin: 4
    frequency: 1000 Hz
    id: pwm_w2
light:
  - platform: rgb
    name: "emily_rgb_strip"
    id: "emily_rgb_strip"
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    effects:
      - pulse:
      - random:
      - strobe:
          name: Strobe
          colors:
            - state: true
              red: 100%
              green: 0%
              blue: 0%
              duration: 500ms
            - state: false
              duration: 250ms
            - state: true
              red: 100%
              green: 100%
              blue: 0%
              duration: 500ms
            - state: false
              duration: 250ms
            - state: true
              red: 0%
              green: 100%
              blue: 0%
              duration: 500ms
            - state: false
              duration: 250ms
            - state: true
              red: 0%
              green: 100%
              blue: 100%
              duration: 500ms
            - state: false
              duration: 250ms
            - state: true
              red: 0%
              green: 0%
              blue: 100%
              duration: 500ms
            - state: false
              duration: 250ms
            - state: true
              red: 100%
              green: 0%
              blue: 100%
              duration: 500ms
            - state: false
              duration: 250ms
            - state: true
              red: 100%
              green: 0%
              blue: 0%
              duration: 500ms
            - state: false
              duration: 250ms
  - platform: monochromatic
    name: "emily_white_strip"
    id: "emily_white_strip"
    output: pwm_w1
  - platform: monochromatic
    name: "emily_reading2"
    id: "emily_reading2"
    output: pwm_w2
          
binary_sensor:
  - platform: gpio
    name: "emily_reading_button2"
    id: "emily_reading_button2"
    pin:
      number: 3
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
    on_press:
      then:
        - light.toggle: emily_reading2
