substitutions:
  device_name: "lights-bathroom"
  friendly_name: "Bathroom Lights"
  deviceicon: "mdi:light"
  lightname_1: "Light 1"
  lightname_2: "Light 2"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

bk72xx:
  board: wb3s

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  reboot_timeout: 24h
  encryption:
    key: "cVCi6rwnqwDgUJEa6sLk/7io+dAI6j1dBBdlxzxsiTs="

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 1h

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Hotspot"
    password: !secret fallback_password

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

captive_portal:

## ------------------ ##
##    Generic Sensors ##
## ------------------ ##
sensor:
  - platform: wifi_signal
    name: Wifi Signal Strength
    update_interval: 60s
  
  - platform: uptime
    name: "Uptime"
    filters:
      - lambda: return x / 86400.0;
    unit_of_measurement: "d"
    accuracy_decimals: 1
    update_interval: 5min

## ---------------- ##
##    Status LED    ##
## ---------------- ##
status_led:
  pin:
    number: P1
    inverted: true

## ---------------- ##
##      Relays      ##
## ---------------- ##
output:
  # Relay 1
  - platform: gpio
    id: relay_1
    pin: P8
  # Relay 2
  - platform: gpio
    id: relay_2
    pin: P26  
  # Relay 3
  - platform: gpio
    id: relay_3
    pin: P24

## ------------ ##
##    Lights    ##
## ------------ ##
light:
  # Light 1
  - platform: binary
    name: ${lightname_1}
    icon: ${deviceicon}
    output: relay_1
    id: light_1

  # Light 2
  - platform: binary
    name: ${lightname_2}
    icon: ${deviceicon}
    output: relay_2
    id: light_2

## ------------ ##
##  Exhaust Fan ##
## ------------ ##
fan:
  - platform: binary
    name: Fan
    output: relay_3
    id: fan_1

## ----------------- ##
##      Buttons      ##
## ----------------- ##
binary_sensor:
  # Button 1
  - platform: gpio
    id: button_1
    pin:
      number: P14
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - light.toggle: light_1
    internal: True

  # Button 2
  - platform: gpio
    id: button_2
    pin:
      number: P9
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - light.toggle: light_2
    internal: True

    # Button 3
  - platform: gpio
    id: button_3
    pin:
      number: P10
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - fan.toggle: fan_1
    internal: True