substitutions:
  device_name: lights-emily
  friendly_name: "Emily Lights"
  hotspot_ssid: "Lights-Emily"
  entity_prefix: "Emily"

packages:
  common_base: !include packages/common-base.yaml
  mcu_overlay: !include packages/bk7231n-cb3s-overlay.yaml
  wifi: !include packages/wifi-outside-and-front.yaml
  reboot_common: !include packages/reboot-common.yaml
  lights_and_fan: !include packages/lights-6914ha-series3.yaml
