substitutions:
  device_name: lights-laundry
  friendly_name: "Laundry Lights"
  hotspot_ssid: "Laundry Lights"
  switch_1_name: None

packages:
  common_base: !include packages/common-base.yaml
  mcu_overlay: !include packages/bk7231n-cb3s-overlay.yaml
  wifi: !include packages/wifi-outside-and-hall.yaml
  reboot_common: !include packages/reboot-common.yaml
  lights: !include packages/lights-6911ha-series3.yaml
