substitutions:
  device_name: lights-entry
  friendly_name: "Entry Lights"
  hotspot_ssid: "Entry Lights Recovery"
  wifi_ssid: !secret wifi_ssid_front
  light_1_group: group.hallway_lights
  light_1_name: "Hallway Entry"
  light_2_name: "Front Deck"
  light_3_name: "Front Yard Sensor Light"
  light_4_name: "Mailbox"

packages:
  common_base: !include packages/common-base.yaml
  esp8266_overlay: !include packages/esp8266-overlay.yaml
  wifi_common: !include packages/wifi-common.yaml
  reboot_common: !include packages/reboot-common.yaml
  lights: !include packages/lights-6904ha-series1.yaml
