substitutions:
  device_name: lights-kitchen
  friendly_name: "Kitchen Lights"
  hotspot_ssid: "EspHomeKitchenLights"
  wifi_ssid: !secret wifi_ssid
  light_2_group: group.hallway_lights
  light_1_name: "Kitchen"
  light_2_name: "Hallway Kitchen"
  light_3_name: "Lounge Dining"
  light_4_name: "Lounge"

packages:
  common_base: !include packages/common-base.yaml
  esp8266_overlay: !include packages/esp8266-overlay.yaml
  wifi_common: !include packages/wifi-common.yaml
  reboot_common: !include packages/reboot-common.yaml
  lights: !include packages/lights-6904ha-series2.yaml

