substitutions:
  device_name: lights-parents

esphome:
  platform: ESP8266
  board: esp01_1m
  name: ${device_name}

# Enable logging
logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 1h

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: EspHomeFallback
    password: !secret fallback_password

captive_portal:

# Enable Home Assistant API
api:
  reboot_timeout: 24h

ota:
  password: !secret ota_password

sensor:
  - platform: wifi_signal
    name: ${device_name} Wifi Signal Strength
    update_interval: 60s
  - platform: uptime
    name: "${device_name} Uptime"
    filters:
      - lambda: return x / 86400.0;
    unit_of_measurement: "d"
    accuracy_decimals: 1
    update_interval: 5min

web_server:
  port: 80

light:
  - platform: binary
    output: relay_light
    id: light1
    name: "Parents"

status_led:
  pin:
    number: GPIO3
    inverted: True

output:
  - platform: gpio
    id: relay_light
    pin: GPIO14
  - platform: template
    id: fan_speed
    type: float
    write_action:
      - then:
        - if:
            condition:
              lambda: return ((state > 0) && (state < .4));
            then:
              - switch.turn_on: relay_fan_1
              - delay: 20ms
              - switch.turn_off: relay_fan_2
              - delay: 20ms
              - switch.turn_off: relay_fan_3
        - if:
            condition:
              lambda: return ((state > .4) && (state < .7));
            then:
              - switch.turn_on: relay_fan_1
              - delay: 20ms
              # Note: the public template for this turns on 1 & 2 and leaves 3 off, but runs at
              # what appears to be full speed. I _think_ tasmota template turns 1 & 3 instead, and
              # that appears to have a better speed gradution.
              # https://www.esphome-devices.com/devices/Deta-Grid-Connect-Smart-Fan-Speed-Controller-with-Touch-Light-Switch 
              # https://templates.blakadder.com/deta_6914HA.html
              - switch.turn_off: relay_fan_2
              - delay: 20ms
              - switch.turn_on: relay_fan_3
        - if:
            condition:
              lambda: return (state > .7);
            then:
              - switch.turn_on: relay_fan_1
              - delay: 20ms
              - switch.turn_on: relay_fan_2
              - delay: 20ms
              - switch.turn_on: relay_fan_3
        - if:
            condition:
              lambda: return (state < 0.01);
            then:
              - switch.turn_off: relay_fan_1
              - delay: 20ms
              - switch.turn_off: relay_fan_2
              - delay: 20ms
              - switch.turn_off: relay_fan_3

binary_sensor:
  - platform: gpio
    id: fan_light_button
    pin:
      number: GPIO16
      mode: INPUT
      inverted: True
    on_press:
      - light.toggle: light1
  
  - platform: gpio
    id: fan_power_button
    pin:
      number: GPIO00
      mode: INPUT
      inverted: True
    on_press:
      then:
        # Toggle the fan off or on, with a special case to set the speed > 0 when turning on
        # It's off and zero after a power cycle and without this logic the button acheives nothing
        - if:
            condition:
              lambda: |-
                return !id(fan_1).state && id(fan_1).speed == 0;
            then:
              - fan.turn_on:
                  id: fan_1
                  speed: 1
            else:
              - fan.toggle: fan_1

  - platform: gpio
    id: fan_speed_button
    pin:
      number: GPIO05
      mode: INPUT
      inverted: True
    on_press:
      then:
        - fan.cycle_speed: fan_1

fan:
  - platform: speed
    id: fan_1
    output: fan_speed
    name: "Parents Fan"
    speed_count: 3

switch:
  - platform: restart
    name: "Parents Lights Reboot"
  - platform: gpio
    id: relay_fan_1
    pin: GPIO13
  - platform: gpio
    id: relay_fan_2
    pin: GPIO04
  - platform: gpio
    id: relay_fan_3
    pin: GPIO15
  - platform: template
    id: update_fan_speed
    optimistic: True
    turn_on_action:
      then:
        - delay: 200ms
        - if:
            condition:
              and:
                - switch.is_off: relay_fan_1
                - switch.is_off: relay_fan_2
                - switch.is_off: relay_fan_3
            then:
              - fan.turn_off: fan_1
        - if:
            condition:
              and:
                - switch.is_on: relay_fan_1
                - switch.is_off: relay_fan_2
                - switch.is_off: relay_fan_3
            then:
              - fan.turn_on:
                  id: fan_1
                  speed: 1
        - if:
            condition:
              and:
                - switch.is_on: relay_fan_1
                - switch.is_on: relay_fan_2
                - switch.is_off: relay_fan_3
            then:
              - fan.turn_on:
                  id: fan_1
                  speed: 2
        - if:
            condition:
              and:
                - switch.is_on: relay_fan_1
                - switch.is_off: relay_fan_2
                - switch.is_on: relay_fan_3
            then:
              - fan.turn_on:
                  id: fan_1
                  speed: 3
