substitutions:
  device_name: toothbrush-monitor-2
  friendly_name: Toothbrush Monitor 2
  hotspot_ssid: "Toothbrush Monitor 2 Hotspot"
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  includes:
    - toothbrush_days_to_show.h

# https://www.elecrow.com/crowpanel-advance-3-5-hmi-esp32-ai-display-480x320-artificial-intelligent-ips-touch-screen.html
# ESP32-S3-WROOM-1U
# 512KB SRAM、8M PSRAM, IL9488 3.5 inch 480x320 display
# Examples:
# https://www.tastethecode.com/smart-home-dashboard-with-esphome-and-crowpanel-hmi-advanced-screen
# https://github.com/Elecrow-RD/CrowPanel-Advance-3.5-HMI-ESP32-S3-AI-Powered-IPS-Touch-Screen-480x320
esp32:
  # variant: esp32s3 - newer versions of esphome should use this instead of board
  # This looks closest, but the following is more generic board: esp32s3box
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf
psram:
  mode: octal
  speed: 80MHz

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  reboot_timeout: 24h
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 1h

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${hotspot_ssid}"
    password: !secret fallback_password

captive_portal:

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

## ------------------ ##
##    Generic Sensors ##
## ------------------ ##
sensor:
  - platform: wifi_signal
    name: "Wifi Signal Strength"
    update_interval: 60s
  
  - platform: uptime
    name: "Uptime"
    filters:
      - lambda: return x / 86400.0;
    unit_of_measurement: "d"
    accuracy_decimals: 1
    update_interval: 5min

bluetooth_proxy:
  active: true

globals:
  # 0 stats, 1 brushing
  - id: _glbl_mode
    type: int
    restore_value: no
    initial_value: "0"
  - id: _glbl_timeout_ticks
    type: int
    restore_value: no
    initial_value: "0"

# make sure json libraries are imported and available in lambdas
json:

font:
  - file: 'arial.ttf'
    id: arialSmall
    size: 14
  - file: 'arial.ttf'
    id: arialMed
    size: 40
  - file: 'arial.ttf'
    id: arialBig
    size: 120

image:
  - file: "frog-small.bmp"
    type: binary
    id: image_frog
    # transparency: chroma_key

# I think these are right - schematic matches example
i2c:
  sda: 15
  scl: 16
  frequency: 400000
  id: i2c_bus

# Backlight configuration
i2c_device:
  id: pca9557
  address: 0x18
  i2c_id: i2c_bus

output:
  - platform: template
    id: backlight_output
    type: binary
    write_action:
      - lambda: |-
          uint8_t config_reg = 0x03;
          uint8_t config_data = 0xFD;
          id(pca9557).write_byte(config_reg, config_data);
          delay(10);
          uint8_t output_reg = 0x01;
          uint8_t output_data = state ? 0x02 : 0x00;
          id(pca9557).write_byte(output_reg, output_data);

light:
  - platform: binary
    name: "Backlight"
    id: backlight
    output: backlight_output
    restore_mode: ALWAYS_ON

number:
  - platform: homeassistant
    id: raw_duration
    entity_id: sensor.toby_toothbrush_duration
    on_value:
      then:
        - lambda: |-
            // switch to either welcome or brushing mode and start the timer
            int old_mode = id(_glbl_mode);
            if (x == 0)
              id(_glbl_mode) = Mode_Welcome;
            else
              id(_glbl_mode) = Mode_Brushing;

            if (old_mode != id(_glbl_mode))
              ESP_LOGI("mode", "%d->%d", old_mode, id(_glbl_mode));

            id(_glbl_timeout_ticks) = 0;

            // Refresh display
            id(backlight).turn_on();
            id(my_display).update();

text_sensor:
  - platform: homeassistant
    id: days_to_show_attr
    entity_id: sensor.toby_brushing_stats
    attribute: days_to_show
    on_value:
      then:
        - lambda: |-
            stats.clear();

            // Allocate JSON document with enough size
            DynamicJsonDocument doc(512);

            auto error = deserializeJson(doc, id(days_to_show_attr).state);
            if (error) {
              ESP_LOGE("days_to_show", "Failed to parse JSON: %s", error.c_str());
              return;
            }

            // doc is now a JSON array
            for (JsonObject day_obj : doc.as<JsonArray>()) {
              DayToShow day;
              strncpy(day.day, day_obj["day"] | "", sizeof(day.day));
              day.am = day_obj["am"].as<float>();
              day.pm = day_obj["pm"].as<float>();
              stats.push_back(day);
            }

            if (stats.size() != 7)
              ESP_LOGE("days_to_show", "Parsed %d days", stats.size());
            else
            {
              ESP_LOGI("days_to_show", "Start %s, AM=%.1f,%.1f,%.1f,%.1f,%.1f,%.1f,%.1f, PM=%.1f,%.1f,%.1f,%.1f,%.1f,%.1f,%.1f",
                stats[0].day,
                stats[0].am, stats[1].am,stats[2].am,stats[3].am,stats[4].am,stats[5].am,stats[6].am,
                stats[0].pm, stats[1].pm,stats[2].pm,stats[3].pm,stats[4].pm,stats[5].pm,stats[6].pm);
            }

            // Refresh display
            id(my_display).update();

# I think these are right - taken from schematic
spi:
  clk_pin: 10
  mosi_pin: 3
  miso_pin: 9
  
color:
  - id: colour_white
    hex: 'ffffff'
  - id: colour_black
    hex: '000000'
  - id: colour_red
    hex: 'ff0000'
  - id: colour_green_text
    hex: '10C000'
  - id: colour_green_frog
    hex: '006D00'
  - id: colour_green_stats
    hex: '006D00'
  - id: colour_gray
    hex: '505050'
  - id: colour_blue
    hex: '0000ff'

# I think this is right - taken from schematic, but example uses something completely different
# platform: rpi_dpi_rgb
display:
  - platform: ili9xxx
    id: my_display
    model: ili9341
    dc_pin: 41
    cs_pin: 40
    rotation: 90
    color_palette: 8BIT
    invert_colors: false
    lambda: |-
 
      if (id(_glbl_mode) == Mode_Welcome)
      {
        it.printf(20, 20, id(arialMed), id(colour_green_text), "Hello Toby");
        it.printf(20, 70, id(arialMed), id(colour_green_text), "I'm ready when");
        it.printf(20, 120, id(arialMed), id(colour_green_text), "you are");
        it.image(200, 140, id(image_frog), id(colour_green_frog), id(colour_black));
      }
      else if (id(_glbl_mode) == Mode_Brushing)
      {
        int duration = (int)(id(raw_duration).state);
        if (duration > TargetDuration)
        {
          it.printf(20, 20, id(arialMed), id(colour_green_text), "Time's up.");
          it.printf(20, 70, id(arialMed), id(colour_green_text), "Great Work!");
          it.image(200, 140, id(image_frog), id(colour_green_frog), id(colour_black));
        }
        else
        {
          it.printf(20, 20, id(arialMed), id(colour_green_text), "Good brushing,");
          it.printf(20, 70, id(arialMed), id(colour_green_text), "keep going");

          int sector = duration / 30;
          it.printf(20, 105, id(arialBig), id(colour_red), "%d", sector);
          int frogX = 100 + (duration % 30) * 4;
          int frogY = 160 - (duration % 30) * 1; 
          ESP_LOGD("frog", "X=%d, Y=%d", frogX, frogY);
          it.image(frogX, frogY, id(image_frog), id(colour_green_frog), id(colour_black));
        }
      }
      else
      {
        it.printf( 2,  40, id(arialSmall), id(colour_white), "Morn");
        it.printf( 2, 140, id(arialSmall), id(colour_white), "Night");

        for (size_t i = 0; i < stats.size(); i++) {
          int am_size = 80 * stats[i].am;
          int pm_size = 80 * stats[i].pm;
          it.filled_rectangle( 40 + 40 * i, 20, 32, 80, id(colour_gray));
          it.filled_rectangle( 40 + 40 * i, 100 - am_size, 32, am_size, stats[i].am >= 1 ? id(colour_green_stats) : id(colour_red));
          it.filled_rectangle( 40 + 40 * i, 120, 32, 80, id(colour_gray));
          it.filled_rectangle( 40 + 40 * i, 200 - pm_size, 32, pm_size, stats[i].pm >= 1 ? id(colour_green_stats) : id(colour_red));
          it.printf( 45 + 40 * i, 205, id(arialSmall), id(colour_white), stats[i].day);
        }
      }

# Not sure about this. It's a different touchscreen in the advanced version, and both schematic
# and example reference address 0x5D, so gt911 copied from the example is probably right.
touchscreen:
  platform: gt911
  id: my_touchscreen
  address: 0x5D
  # update_interval: 50ms
  # threshold: 400
  # calibration:
  #   x_max: 3848
  #   x_min: 320
  #   y_max: 3848
  #   y_min: 240
  # transform:
  #   mirror_x: false
  #   mirror_y: false
  #   swap_xy: false
  on_touch:
    - lambda: |-
        ESP_LOGI("touched", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
                 touch.x, touch.y, touch.x_raw, touch.y_raw);

        if (id(_glbl_mode) == Mode_Off)
        {
          ESP_LOGI("mode", "Off->Stats");
          
          // Display Stats
          id(_glbl_mode) = Mode_Stats;
          id(backlight).turn_on();
          id(my_display).update();
          id(_glbl_timeout_ticks) = 0;
        }

interval:
- interval: 1s
  then:
    - lambda: |-
        if (id(_glbl_mode) == Mode_Off)
          return;

        id(_glbl_timeout_ticks) += 1;
        ESP_LOGD("mode", "Ticks=%d", id(_glbl_timeout_ticks));

        // wait 2 minutes to start brushing
        if (id(_glbl_mode) == Mode_Welcome && id(_glbl_timeout_ticks) >= 120 )
        {
          ESP_LOGI("mode", "Welcome->Off");
          
          // Display off
          id(_glbl_mode) = Mode_Off;
          id(backlight).turn_off();
          id(my_display).update();
        }
        // Display stats 5s after stopping brushing
        else if (id(_glbl_mode) == Mode_Brushing && id(_glbl_timeout_ticks) >= 5 )
        {
          ESP_LOGI("mode", "Brushing->Stats");

          // Display stats
          id(_glbl_mode) = Mode_Stats;
          id(my_display).update();
        }
        // Display stats for 60s
        else if (id(_glbl_mode) == Mode_Stats && id(_glbl_timeout_ticks) >= 60 )
        {
          ESP_LOGI("mode", "Stats->Off");
          
          // Display off
          id(_glbl_mode) = Mode_Off;
          id(backlight).turn_off();
          id(my_display).update();
        }

