substitutions:
  device_name: toothbrush-monitor
  friendly_name: "Toothbrush Monitor"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  includes:
    - toothbrush_days_to_show.h

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  reboot_timeout: 24h
  encryption:
    key: "cVCi6rwnqwDgUJEa6sLk/7io+dAI6j1dBBdlxzxsiTs="

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid_hall
  password: !secret wifi_password
  reboot_timeout: 1h

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Hotspot"
    password: !secret fallback_password

# not enough flash for normal web server or captive portal fallbacks

## ------------------ ##
##    Generic Sensors ##
## ------------------ ##
sensor:
  - platform: wifi_signal
    name: "Wifi Signal Strength"
    update_interval: 60s
  
  - platform: uptime
    name: "Uptime"
    filters:
      - lambda: return x / 86400.0;
    unit_of_measurement: "d"
    accuracy_decimals: 1
    update_interval: 5min

# bluetooth_proxy:
#   active: true

globals:
  # 0 stats, 1 brushing
  - id: _glbl_mode
    type: int
    restore_value: no
    initial_value: "0"
  - id: _glbl_timeout_ticks
    type: int
    restore_value: no
    initial_value: "0"

# make sure json libraries are imported and available in lambdas
json:

font:
  - file: 'arial.ttf'
    id: arialSmall
    size: 14
  - file: 'arial.ttf'
    id: arialMed
    size: 40
  - file: 'arial.ttf'
    id: arialBig
    size: 120

image:
  - file: "frog-small.bmp"
    type: binary
    id: image_frog
    # transparency: chroma_key

switch:
  # I don't think there's a physical LED on the board, just a gpio for one, but also an indicator
  # on the screen for the led state.
  - platform: gpio
    name: "backlight"
    id: backlight
    pin: 27
    inverted: no
    restore_mode: ALWAYS_ON

number:
  - platform: homeassistant
    id: raw_duration
    entity_id: sensor.toby_toothbrush_duration
    on_value:
      then:
        - lambda: |-
            // switch to either welcome or brushing mode and start the timer
            int old_mode = id(_glbl_mode);
            if (x == 0)
              id(_glbl_mode) = Mode_Welcome;
            else
              id(_glbl_mode) = Mode_Brushing;

            if (old_mode != id(_glbl_mode))
              ESP_LOGI("mode", "%d->%d", old_mode, id(_glbl_mode));

            id(_glbl_timeout_ticks) = 0;

            // Refresh display
            id(backlight).turn_on();
            id(my_display).update();

text_sensor:
  - platform: homeassistant
    id: days_to_show_attr
    entity_id: sensor.toby_brushing_stats
    attribute: days_to_show
    on_value:
      then:
        - lambda: |-
            stats.clear();

            // Allocate JSON document with enough size
            DynamicJsonDocument doc(512);

            auto error = deserializeJson(doc, id(days_to_show_attr).state);
            if (error) {
              ESP_LOGE("days_to_show", "Failed to parse JSON: %s", error.c_str());
              return;
            }

            // doc is now a JSON array
            for (JsonObject day_obj : doc.as<JsonArray>()) {
              DayToShow day;
              strncpy(day.day, day_obj["day"] | "", sizeof(day.day));
              day.am = day_obj["am"].as<float>();
              day.pm = day_obj["pm"].as<float>();
              stats.push_back(day);
            }

            if (stats.size() != 7)
              ESP_LOGE("days_to_show", "Parsed %d days", stats.size());
            else
            {
              ESP_LOGI("days_to_show", "Start %s, AM=%.1f,%.1f,%.1f,%.1f,%.1f,%.1f,%.1f, PM=%.1f,%.1f,%.1f,%.1f,%.1f,%.1f,%.1f",
                stats[0].day,
                stats[0].am, stats[1].am,stats[2].am,stats[3].am,stats[4].am,stats[5].am,stats[6].am,
                stats[0].pm, stats[1].pm,stats[2].pm,stats[3].pm,stats[4].pm,stats[5].pm,stats[6].pm);
            }

            // Refresh display
            id(my_display).update();

spi:
  clk_pin: 14
  mosi_pin: 13
  miso_pin: 12
  
color:
  - id: colour_white
    hex: 'ffffff'
  - id: colour_black
    hex: '000000'
  - id: colour_red
    hex: 'ff0000'
  - id: colour_green_text
    hex: '10C000'
  - id: colour_green_frog
    hex: '006D00'
  - id: colour_green_stats
    hex: '006D00'
  - id: colour_gray
    hex: '505050'
  - id: colour_blue
    hex: '0000ff'


display:
  - platform: ili9xxx
    id: my_display
    model: ili9341
    dc_pin: 2
    cs_pin: 15
    rotation: 90
    color_palette: 8BIT
    invert_colors: false
    lambda: |-
      
      if (id(_glbl_mode) == Mode_Welcome)
      {
        it.printf(20, 20, id(arialMed), id(colour_green_text), "Hello Toby");
        it.printf(20, 70, id(arialMed), id(colour_green_text), "I'm ready when");
        it.printf(20, 120, id(arialMed), id(colour_green_text), "you are");
        it.image(200, 140, id(image_frog), id(colour_green_frog), id(colour_black));
      }
      else if (id(_glbl_mode) == Mode_Brushing)
      {
        int duration = (int)(id(raw_duration).state);
        if (duration > TargetDuration)
        {
          it.printf(20, 20, id(arialMed), id(colour_green_text), "Time's up.");
          it.printf(20, 70, id(arialMed), id(colour_green_text), "Great Work!");
          it.image(200, 140, id(image_frog), id(colour_green_frog), id(colour_black));
        }
        else
        {
          it.printf(20, 20, id(arialMed), id(colour_green_text), "Good brushing,");
          it.printf(20, 70, id(arialMed), id(colour_green_text), "keep going");

          int sector = duration / 30;
          it.printf(20, 105, id(arialBig), id(colour_red), "%d", sector);
          int frogX = 100 + (duration % 30) * 4;
          int frogY = 160 - (duration % 30) * 1; 
          ESP_LOGD("frog", "X=%d, Y=%d", frogX, frogY);
          it.image(frogX, frogY, id(image_frog), id(colour_green_frog), id(colour_black));
        }
      }
      else
      {
        it.printf( 2,  40, id(arialSmall), id(colour_white), "Morn");
        it.printf( 2, 140, id(arialSmall), id(colour_white), "Night");

        for (size_t i = 0; i < stats.size(); i++) {
          int am_size = 80 * stats[i].am;
          int pm_size = 80 * stats[i].pm;
          it.filled_rectangle( 40 + 40 * i, 20, 32, 80, id(colour_gray));
          it.filled_rectangle( 40 + 40 * i, 100 - am_size, 32, am_size, stats[i].am >= 1 ? id(colour_green_stats) : id(colour_red));
          it.filled_rectangle( 40 + 40 * i, 120, 32, 80, id(colour_gray));
          it.filled_rectangle( 40 + 40 * i, 200 - pm_size, 32, pm_size, stats[i].pm >= 1 ? id(colour_green_stats) : id(colour_red));
          it.printf( 45 + 40 * i, 205, id(arialSmall), id(colour_white), stats[i].day);
        }
      }

touchscreen:
  platform: xpt2046
  id: my_touchscreen
  cs_pin: 33
  update_interval: 50ms
  threshold: 400
  calibration:
    x_max: 3848
    x_min: 320
    y_max: 3848
    y_min: 240
  transform:
    mirror_x: false
    mirror_y: false
    swap_xy: false
  on_touch:
    - lambda: |-
        ESP_LOGI("touched", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
                 touch.x, touch.y, touch.x_raw, touch.y_raw);

        if (id(_glbl_mode) == Mode_Off)
        {
          ESP_LOGI("mode", "Off->Stats");
          
          // Display Stats
          id(_glbl_mode) = Mode_Stats;
          id(backlight).turn_on();
          id(my_display).update();
          id(_glbl_timeout_ticks) = 0;
        }

interval:
- interval: 1s
  then:
    - lambda: |-
        if (id(_glbl_mode) == Mode_Off)
          return;

        id(_glbl_timeout_ticks) += 1;
        ESP_LOGD("mode", "Ticks=%d", id(_glbl_timeout_ticks));

        // wait 2 minutes to start brushing
        if (id(_glbl_mode) == Mode_Welcome && id(_glbl_timeout_ticks) >= 120 )
        {
          ESP_LOGI("mode", "Welcome->Off");
          
          // Display off
          id(_glbl_mode) = Mode_Off;
          id(backlight).turn_off();
          id(my_display).update();
        }
        // Display stats 5s after stopping brushing
        else if (id(_glbl_mode) == Mode_Brushing && id(_glbl_timeout_ticks) >= 5 )
        {
          ESP_LOGI("mode", "Brushing->Stats");

          // Display stats
          id(_glbl_mode) = Mode_Stats;
          id(my_display).update();
        }
        // Display stats for 60s
        else if (id(_glbl_mode) == Mode_Stats && id(_glbl_timeout_ticks) >= 60 )
        {
          ESP_LOGI("mode", "Stats->Off");
          
          // Display off
          id(_glbl_mode) = Mode_Off;
          id(backlight).turn_off();
          id(my_display).update();
        }

