# There are outputs from the motor controller for when the motors are running in either direction,
# when the door is at either limit, and a pulse event on the worm gear.
# I had dreams of showing the correct partial position, but I wasted a lot of time on it and the
# internal ESP pull ups and downs gave me grief. (I had a voltage divider connected to D8 but the
# internal pull down caused problems.) The motor up & down inputs are on pin 1 & 2, are normally
# 24v, 0v when running, and 30v spikes. I wanted to use a transistor to pull D2 & D3 down but think
# it's cause problems on D3 at boot. I gave up, it's ok to have just the limit inputs.
substitutions:
  device_name: "Garage Wemos D1"
  sensor_name: "Garage Door"

esphome:
  name: wemosd1-garage
  on_boot:
    priority: 600
    then:
      - cover.template.publish:
          id: garage
          # assuming opening where neither limit is active
          # and it can change to either open or closed
          state: OPEN
          current_operation: OPENING

esp8266:
  board: d1_mini

# Enable logging
logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid_front
  password: !secret wifi_password
  min_auth_mode: WPA2
  reboot_timeout: 1h

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wemosd1-Garage"
    password: !secret fallback_password

captive_portal:

# Enable Home Assistant API
api:
  reboot_timeout: 24h

ota:
  platform: esphome
  password: !secret ota_password

external_components:  
  - source:
      type: git
      url: https://github.com/muxa/esphome-state-machine
    refresh: 1h

# The web_server & sensor components can be removed without affecting core functionaility.
web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

sensor:
  - platform: wifi_signal
    name: "${device_name} WiFi Signal"
    update_interval: 5min

  - platform: uptime
    name: "Uptime"
    filters:
      - lambda: return x / 86400.0;
    unit_of_measurement: "d"
    accuracy_decimals: 1
    update_interval: 5min

switch:
  - platform: gpio
    internal: true
    name: "${sensor_name} Toggle"
    pin: D1
    id: garage_relay
    icon: "mdi:garage"
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: garage_relay

binary_sensor:
  - platform: gpio
    name: "Fully Closed"
    pin:
      number: D7
      inverted: true
      mode: INPUT
    filters:
      - delayed_on: 200ms
      - delayed_off: 200ms
    on_press:
      - state_machine.transition: DETECTED_CLOSED
    on_release:
      - state_machine.transition: DETECTED_OPENING
  - platform: gpio
    name: "Fully Open"
    pin:
      number: D6
      inverted: true
      mode: INPUT
    filters:
      - delayed_on: 200ms
      - delayed_off: 200ms
    on_press:
      - state_machine.transition: DETECTED_OPEN
    on_release:
      - state_machine.transition: DETECTED_CLOSING

text_sensor:
  - platform: state_machine
    id: garage_state_machine
    name: Garage Door State Machine State

state_machine:
  - name: "State Machine"
    id: garage_sm
    diagram: mermaid
    initial_state: OPENING
    states:
      - name: CLOSED
        on_enter:
          - cover.template.publish:
              id: garage
              state: CLOSED
              current_operation: IDLE
      - name: OPENING
        on_enter:
          - cover.template.publish:
              id: garage
              state: OPEN
              current_operation: OPENING
      - name: OPEN
        on_enter:
          - cover.template.publish:
              id: garage
              state: OPEN
              current_operation: IDLE
      - name: CLOSING
        on_enter:
          - cover.template.publish:
              id: garage
              state: OPEN
              current_operation: CLOSING
    inputs:
      - name: DETECTED_OPENING
        transitions:
          - CLOSED -> OPENING
          - CLOSING -> OPENING
          # If the closed limit sensor turns off while in open we can assume it's actually opening
          - OPEN -> OPENING
      - name: DETECTED_OPEN
        transitions:
          - CLOSING -> OPEN
          - CLOSED -> OPEN
          - OPENING -> OPEN
      - name: DETECTED_CLOSING
        transitions:
          - OPENING -> CLOSING
          - OPEN -> CLOSING
      - name: DETECTED_CLOSED
        transitions:
          - CLOSING -> CLOSED
          - OPENING -> CLOSED
          # Don't trust it to go open->closed, something's going wrong with the sensors, stay in
          # some sort of open state
          # - OPEN -> CLOSED
      - name: REQUEST_OPEN
        transitions:
          - CLOSED -> OPENING
          - CLOSING -> OPENING
        on_input:
          - switch.turn_on: garage_relay
      - name: REQUEST_CLOSE
        transitions:
          - OPEN -> CLOSING
          - OPENING -> CLOSING
        on_input:
          - switch.turn_on: garage_relay

cover:
  - platform: template
    name: "${sensor_name}"
    id: garage
    device_class: garage
    assumed_state: true
    open_action: 
      - state_machine.transition: REQUEST_OPEN
    close_action:
      - state_machine.transition: REQUEST_CLOSE
    stop_action:
      - switch.turn_on: garage_relay
