substitutions:
  device_name: "Garage Wemos D1"
  sensor_name: "Garage Door"
  open_duration: 30s
  distance_threshold: "0.9"
  # don't trust any ridiculously small measurements
  distance_threshold_min: "0.25"

esphome:
  name: wemosd1-garage
  platform: ESP8266
  board: d1_mini
  on_boot:
    priority: 600
    then:
      - cover.template.publish:
          id: garage
          state: OPEN
          current_operation: IDLE

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  reboot_timeout: 24h

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_garage_ssid
  password: !secret wifi_garage_password 
  reboot_timeout: 1h

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wemosd1-Garage Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

external_components:  
  - source:
      type: git
      url: https://github.com/muxa/esphome-state-machine
    refresh: 1h

sensor:
  - platform: wifi_signal
    name: "${device_name} WiFi Signal"
    update_interval: 5min

  - platform: uptime
    name: "${device_name} Uptime"
    filters:
      - lambda: return x / 86400.0;
    unit_of_measurement: "d"
    accuracy_decimals: 1
    update_interval: 5min

# Read the zigbee door sensor from home assistant
# The physical position means we reliably detect when the door is closed but the sensor state
# goes on/off when the door is open/closed respectively, so on_press fires when it begins to
# open, and on_release fires when closed.
binary_sensor:
  - platform: homeassistant
    name: "Zigbee door sensor (from Home Assistant)"
    entity_id: binary_sensor.garage_door_closed_stop
    publish_initial_state: true
    on_press:
      - state_machine.transition: DETECTED_OPENING
    on_release:
      - state_machine.transition: DETECTED_CLOSED
    

  # Disable this sensor of when the button is pressed, I haven't wired it up and it's not very
  # important, I know the door state regardless of the button.
  # - platform: gpio
  #   pin:
  #     number: D0
  #     mode: INPUT_PULLUP
  #   name: "${device_name} Button Pressed"
  #   filters:
  #     - delayed_on: 100ms
  #   # If it wasn't our code that triggered the button input to the motor transition the state machine
  #   on_press:
  #     - if:
  #         condition:
  #           - switch.is_off: garage_relay
  #         then:
  #           - state_machine.transition: PRESS
  
switch:
  - platform: gpio
    internal: true
    name: "${sensor_name} Toggle"
    pin: D8
    id: garage_relay
    icon: "mdi:garage"
    on_turn_on:
      - delay: 1s
      - switch.turn_off: garage_relay

text_sensor:
  - platform: state_machine
    id: garage_state_machine
    name: Garage Door State Machine State

state_machine:
  - name: "${sensor_name} State Machine"
    id: garage_sm
    diagram: mermaid
    initial_state: OPEN
    states:
      - name: CLOSED
        on_enter:
          - cover.template.publish:
              id: garage
              state: CLOSED
              current_operation: IDLE
      - name: OPENING
        on_enter:
          - cover.template.publish:
              id: garage
              state: OPEN
              current_operation: OPENING
          - delay: ${open_duration}
          - state_machine.transition: TIMEOUT
      - name: OPEN
        on_enter:
          - cover.template.publish:
              id: garage
              state: OPEN
              current_operation: IDLE
      - name: CLOSING
        on_enter:
          - cover.template.publish:
              id: garage
              state: OPEN
              current_operation: CLOSING
    inputs:
      - name: PRESS
        transitions:
          - CLOSED -> OPENING
          - OPENING -> CLOSING
          - CLOSING -> OPENING
          - OPEN -> CLOSING
      - name: TIMEOUT
        transitions:
          - OPENING -> OPEN
        on_input:
          - logger.log: "Timeout reached"
      - name: DETECTED_OPENING
        transitions:
          - CLOSED -> OPENING
          - CLOSING -> OPENING
          - OPEN -> OPENING
      - name: DETECTED_CLOSED
        transitions:
          - CLOSING -> CLOSED
          - OPEN -> CLOSED
          - OPENING -> CLOSED
      - name: REQUEST_OPEN
        transitions:
          - CLOSED -> OPENING
          - CLOSING -> OPENING
        on_input:
          - switch.turn_on: garage_relay
      - name: REQUEST_CLOSE
        transitions:
          - OPEN -> CLOSING
          - OPENING -> CLOSING
        on_input:
          - switch.turn_on: garage_relay

cover:
  - platform: template
    name: "${sensor_name}"
    id: garage
    device_class: garage
    assumed_state: true
    open_action: 
      - state_machine.transition: REQUEST_OPEN
    close_action:
      - state_machine.transition: REQUEST_CLOSE
    stop_action:
      - switch.turn_on: garage_relay
